### ISSUE TITLE
test_function automatic response

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#106]
@filipsch were you going to remove the 'You should specify one argument without naming it.' from the auto-response as students may be confused by the use the term 'naming'?

<img width="308" alt="screenshot 2016-10-03 17 53 53" src="https://cloud.githubusercontent.com/assets/4182382/19055539/716bd760-8992-11e6-8833-65f11e64a2b0.png">

**Comment by hugobowne** [comment]
ps yes, im now beginning to work with v2!

**Comment by filipsch** [comment]
Will remove it.

**Comment by machow** [comment]
Now in prod. Fixed in commit 0c145b170dd1aeb3ebc9e1ce3ac59c52f7e0b250
