### ISSUE TITLE
test_function_v2 wiki

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#109]
in the documentation for `test_function_v2()`, it says `test_function` a number of times. e.g.

<img width="766" alt="screenshot 2016-10-04 15 01 47" src="https://cloud.githubusercontent.com/assets/4182382/19088327/a811423a-8a43-11e6-85bd-2d154d95bf93.png">

there are also a number of other places I saw it

**Comment by filipsch** [comment]
@hugobowne Thanks for mentioning this. As they are small typos, feel free to fix them yourself by updating the wiki. Together we stand united!
