### ISSUE TITLE
test_function_definition: function argument parameter 'not defined'

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#11]
datacamp is throwing an error here wrt parameter passed to def:

https://campus.datacamp.com/courses/1113/2464?ex=4

screenshot attached

<img width="1273" alt="screen shot 2016-05-27 at 11 57 51 am" src="https://cloud.githubusercontent.com/assets/4182382/15613844/843d460c-2403-11e6-8882-29cd3ff9ed2a.png">

**Comment by vincentvankrunkelsven** [comment]
Scoping issue, I'm going to bundle it with #10
