### ISSUE TITLE
Spec Refactor: test expression/function calls on either output, result, or error

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#119]
They appear to be doing the same things, and repeating a lot of code. This would make getting the "big picture" much easier for maintaining the code, but also for API docs.

**edit: I think we should wait to implement other things, before completing this task, since we'll need to change how errors are handled when running the backend from pythonwhat**

**Comment by machow** [comment]
After pairing, this seems much more doable. We'll change this within tasks...

```{python}
try:
    #something
except: return None
```

to

```{python}
try: #something
except Exception as e: return e
```

**Comment by filipsch** [comment]
... that is assuming that __every__ Exception can be pickled/dilled? ;)

**Comment by machow** [comment]
up on production. I can't imagine a case where someone makes an undillable subclass of Exception, but if it can't be dilled, a converter can always be written for it ;). This would have been an issue for testing expression errors (e.g. test_function_definition) before the change (and now).
