### ISSUE TITLE
using test_student_typed within a test_if_exp

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#120]
Pairing w/Hugo, it looked like if `test_student_typed` below contained the whole if expression, the test still passed.

**\* =solution

``` python
L3 = [i**2 if i> 5 else 0 for i in range(0,10)]
```

**\* =sct

``` python
test_list_comp(comp_iter = lambda: test_expression_result(),
                         body = lambda: test_if_exp(
                                   body=lambda: test_student_typed(r"\s*i\*\*2\s*"),
                                   test= lambda: test_expression_result(context_vals = [6]),
                                   orelse= lambda: test_expression_result()))
```

**Comment by machow** [comment]
Below is a simplified sct...

*** =solution
```{python}
test_if_exp(body=test_student_typed(r"\s*2\*\*2\s*if"))  # Note that trailing "if" shouldn't match!
```

*** =sct
```{python}
2**2 if 2 > 5 else 0
```

These are the code strings for each part of the if else expression that test_student_typed receives...

test: `2`
body: `2**2 if 2 > 5`
orelse: `0`

in other words, the orelse portion is correct, but the other two are off. I'm guessing it has to do with how we go from ast -> code string. We recently added test_if_exp as a slight adaptation of test_if_else, but there must be some code for utils_ast that needs to added.

**Comment by machow** [comment]
@filipsch I've uploaded a gist that provides an overview of the differences between ASTs for block if-else and inline ifs. The crux is that things like the body of a block if statement is a list of expressions, whereas an inline if it's a single node. I have no idea why `utils_ast` is assigning the wrong end points, but it probably comes down to doing something special to parse lists of expressions.

In terms of time, I'm afraid to touch anything in `utils_ast`...

**Comment by machow** [comment]
just a note, I spent an hour on the plane trying to comb through utils_ast, and have no idea how it works..

**Comment by filipsch** [comment]
@machow `utils_ast` is code that I've borrowed from the `thonny` project, and improved along the way. We can go over it in our next checkin.

**Comment by machow** [comment]
sure thing--I remembered you mentioned that, and don't hold any of my confusion against you!

**Comment by machow** [comment]
This is not going to be solved anytime soon--the current workaround is to use [`has_equal_ast`](http://pythonwhat.readthedocs.io/en/latest/simple_tests/has_equal_ast.html#has-equal-ast), which generally produce a similar, but more robust test than `test_student_typed`.

**Comment by filipsch** [comment]
This is a non-issue now that we have the entire V2 spec that is more robust about 'zooming in' on elements of the submission. I'm not going to invest time in this. If anything similar pops up, feel free to open new issue.

**Comment by machow** [comment]
@filipsch this was a bug in thonny, so likely solved when you replaced it!
