### ISSUE TITLE
Spec Refactor: split test_function_v2 into sub-tests

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#123]
### Problem

Many pythonwhat test_* functions allowing breaking a submission into parts. For example, `test_list_comp` has three parts:

``` python
[BODY for i in COMP_ITER if IFS]
```

The benefit of this setup is that it allows nesting test_* functions to test parts inside parts, etc..

Since test_function[_v2] does not break code into parts, SCT writers don't have fine-grain access to function calls.
### Solution

**This is likely wrong, but I'm putting it here to start discussion**

Essentially, allow arguments of a function call to be parts, with two ways of selecting parts: from the "outside" or "inside".
1. "outside": Allow access to parts via the AST node entires (args, kwargs). This is similar to how functions like test_list_comp work.
2. "inside": Allow access to parts via the bound_arguments mapping that test_function_v2 currently does.

These two approaches differ only how they select argument expressions. For example, on the following submission...

``` python
def func(a, *args):
    pass

data = [1,2,3,4]
func(*data)
```

(1) can select a starred argument input, or an argument by its position or keyword specified.  (2) could select using the argument it was (or would be) bound to. AFAIK the current implementations are using strategy (2), by binding the values from the submission/solution environments to the function signature.

I've split test_function_v2 into several functions, to separate some of the logic in commit 9c86607629b4b81f8ae6a921ae2927f8adda0f66. To make it similar to other functions using sub-tests, users should be able have the option of specifying subtests to essentially replace `build_test` in `test_args`, and the argument information necessary should be derivable from state (i.e., the current state expression for student and submission are the argument expressions). This is how functions like `test_list_comp` work.

@filipsch thoughts? I'll be working on specc'ing easier test_* functions today, but wanted to get the ball rolling on this, since it seems like the most challenging part of the refactor. Note that I simplified test_function_v2 to use test_or internally!

Edit:
### Parts layout

``` python
def func(a, *args, b=1, **kwargs): pass
```
#### (1) "outer" perspective:

``` python
func(POSARGS[1], POSARGS[2], KWARGS['b'], KWARGS['c'])
```

where each part corresponds to a posargs or kwargs entry on the Call Node
#### (2) "inner" perspective:

``` python
func(A=<ast>, ARGS=<ast>, B=<ast>, KWARGS=<ast>)
```

where a list of <ast> expressions may need to be bound to arguments, as in the case of *args.

For example,

``` python
def func(a, *args): pass

func(*[1,2])
```

produces an AST of

```
Module(body=[
    FunctionDef(name='func', args=arguments(args=[
        arg(arg='a', annotation=None),
      ], vararg=arg(arg='args', annotation=None), kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=[
        Pass(),
      ], decorator_list=[], returns=None),
    Expr(value=Call(func=Name(id='func', ctx=Load()), args=[
        Starred(value=List(elts=[
            Num(n=1),
            Num(n=2),
          ], ctx=Load()), ctx=Load()),
      ], keywords=[])),
  ])
```

so the arguments `a` and `b` would correspond to `Num(n=1)` and `Num(n=2)` respectively.

**Comment by machow** [comment]
Actually, looking at `build_test`, I guess it should be quite easy if its arguments `stud` and `sol` are just state.student_context and state.solution_context.

**Comment by filipsch** [comment]
@machow interesting stuff. I think the idea you put forth makes sense! We can talk about this in our checkins. Until then I indeed think you can start with the other, more straightforward stuff. Feel free to structure your work in issues to make it easier to follow up with progress.

**Comment by machow** [comment]
Now it seems easier to just implement the new functionality needed for test function in the new spec, rather than battling the code inside `test_function_v2`.

TODO:

- [ ] pull out logic for matching up student/solution args
- [ ] make args into parts, ensure `check_args` works
- [ ] unit tests for deeply nested calls, etc

**Comment by machow** [comment]
closing, since resolved by check_function implementation.
