### ISSUE TITLE
Cheatsheet with subtest parts

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#125]
For `test_list_comp` and friends, it would greatly help my sanity to lay out the parts the break code into. For example, `test_list_comp` is 

[BODY for i in COMP_ITER if IFS]

**Comment by machow** [comment]
[here!](https://github.com/datacamp/pythonwhat/wiki/parts_cheatsheet)

**Comment by filipsch** [comment]
Nice! Good idea
