### ISSUE TITLE
Spec Refactor: how do tests know when to do cleanup?

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#129]
Under the proposed spec, `test_with` might look like...

``` python
cwb = ex().check_with(1).check_body()
cwb.test_function(MORE_ARGS)
cwb.test_expression_output(MORE_ARGS)
```

The current implementation of `test_with` runs a piece of code after all subtests. How would this be done for the code above? One solution would be to have `check_body()` put the cleanup code in a callback on state, and this could be run after certain statements, such as ones that change state. So in this case:

``` python
cw = ex().check_with(1)
cw.check_body().test_function(MORE_ARGS).check_arg('a') # ETC
cw.check_context().test_function(MORE_ARGS)
```

it would call cleanup when `check_context` is called, not when `check_arg` is called. This seems complex, though. In general, if there is a lot of wrapping up like this, using chains like this could be problematic. Another solution is to use something like `.run()` at the end, but this would get fairly wordy.

**Comment by filipsch** [comment]
@machow might make sense to add some stuff we've discussed on the phone so we don't forget about them!

**Comment by machow** [comment]
For sure--I think the most important message I took out of our discussion (and some probing today) is that oftentimes code that would clean up after a certain set of sub_tests (e.g. for the body of a with statement), can reasonably just be run for each sub_test.

In cases where it would impact performance we can subclass state, or something similar.

**Comment by machow** [comment]
This situation pops up in a more serious way with testing the ifs of `test_list_comp`. In this case, the `ifs` argument is looped through, and the message is adjusted so that you could says "check if 1", "check if 2", etc...

**Comment by machow** [comment]
Closing, `test_with` was a special case that the `with_context` subtest running function fixes. (see #135 )
