### ISSUE TITLE
Rethinking how pythonwhat raises errors for instructors

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#130]
In the current code, pythonwhat often runs tests twice. The first is to potentially raise an error for instructors, while the second is to test the submission. For example, looking at whether an object is defined in `test_object`...

``` python
    if not isDefinedInProcess(name, solution_process):
        raise NameError("%r not in solution environment " % name)

    rep.do_test(DefinedProcessTest(name, student_process, Feedback(undefined_msg)))
```

the first check raises an error if it is not defined in the solution. This is for the instructor, but essentially is just a duplication of testing. **Would it work to just run solution code as the submission code for instructors (e.g. remove the if block)?**

There are a couple benefits
1. The checks for instructors only need to run while developing, but currently run every time.
2. May cut down on a lot of duplication.
3. Reflects that the solution code is just one of many passing submissions being tested.
4. Matches how the validator currently operates

**Comment by machow** [comment]
From pairing with @filipsch it sounds like in most cases this can be done without problem. I'll keep an eye out for cases where the message in an exception differs from its corresponding test. CC @hugobowne in case he is using the exceptions.

To be clear, we're talking about removing the error messages mentioned in #89 :

![image](https://cloud.githubusercontent.com/assets/2574498/19486649/3f0522f8-952d-11e6-85ec-e4b36b444441.png)

They generally repeat the default messages you would get if you copied the solution code and ran it as submission code (which it sounds like is the approach instructors use to test).

**Comment by hugobowne** [comment]
@machow in the above case, for example, what would the error message be ?

The challenge for me is, when writing SCTs after having written working solution code, knowing what the problem with my SCT is

**Comment by machow** [comment]
I think that error is about SCT syntax, so it would stay the same for now (but having it blurred out should be fixed down the road). Now that I look at it, most of what this would change shouldn't change much what you see. This would affect only cases like below, where there is an error because the SCT is trying to check something that isn't in the solution...

*** =submission
```{python}
a = 1
```

*** =solution

```{python}
b = 1
```

*** =sct

```{python}
test_object('a')
```

In this case, since no object `a` was defined in the solution, it would raise an error (the hard to read red text). But the error pythonwhat raises is very similar to what it would tell a student, in the case where the solution was `a = 1`, but the submission used only `b = 1`.

The messages are...

Error: `a` not in solution environment
Student message: Have you defined `a`?

**Comment by hugobowne** [comment]
FYI these messages are no longer blurred out :-D

**Comment by machow** [comment]
closing for now, at some point it may be worth implementing error messages for instructors using their own exception, (SolutionError or something), so that it can be reliably detected and dealt with in try/except blocks.
