### ISSUE TITLE
Bokeh needs a manual converter or workarounds

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#134]
See https://github.com/datacamp/campus-app/issues/289

![screenshot 2016-10-18 14 16 43](https://cloud.githubusercontent.com/assets/18146758/19490541/8c9adc00-953d-11e6-8d4a-18d50736aee7.png)

[explained in docs here](https://github.com/datacamp/pythonwhat/wiki/Processes)

**Comment by hugobowne** [comment]
@machow great. as you know, we use `test_function_v2` to get around this. However, the same error appears when we attempt to specify the `params`

SCT:
```
sig - signature(param("obj", param.POSITIONAL_OR_KEYWORD))
test_function_v2("bokeh.io.show", params=["obj"], signature=sig)
```

error thrown:

<img width="1015" alt="screenshot 2016-10-19 12 59 53" src="https://cloud.githubusercontent.com/assets/4182382/19528944/0119611e-95fc-11e6-8769-9dfa9193a166.png">

Once we have SCTs drafted for Bokeh course (EOW; early next week at latest), I'll loop back and let you know the stumbling blocks

**Comment by machow** [comment]
You can also do something like `test_function(STUFF, args=[])` to produce the same kind of behavior in `test_function`. 

If you end up re-writing specific [converters](https://github.com/datacamp/pythonwhat/wiki/Processes) to test arguments a lot, we can add them to pythonwhat.

**Comment by machow** [comment]
can reopen when there is a specific converter that needs to be implemented.
