### ISSUE TITLE
generalizing test_with's use of __env__

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#135]
For code like...

``` python
with open('file.txt') as f, open('file2.txt') as f2:
    f.read()
    f2.read()
```

`test_with` creates a copy of the environment in each process, so it can run subtests. In other words, in the code above it would
1. run each `open` command in the process, and assign the resulting values to `f` and `f2`
2. put `f` and `f2` in a special variable `__env__`, which is a copy of the process's environment
3. when running a subtest, if `__env__` exists, use that instead of the process environment (so you can have access to `f` and `f2`, which may be referenced in the body).
### Problem

This setup appears specific to `test_with`, but seems like it would apply to loops as well, and is a variation on the idea of `context_values`. Can the `test_with` case be expressed as a special case of `context_values`, and (if useful) can this be used for the body of test_for_loop? (maybe it already is?)

**edit:** I just noticed that test_for_loop sets subtests up to use context_values
### Solution

With the new spec, it seems like having a function to set context values should remove the need for this special case, e.g. something like...

``` python
# for i in range(10): print(i)
check_for_loop().set_context(i=5).check_body() # etc ....

# corresponding to code up top
check_with().set_context('f', 'f2').check_body() # etc ....

# where e is the name of the exception
check_try_except().set_context('e').check_handler('something') # etc ...
```

Here, a value can be set explicitly (`i = 5`) or to be the evaluated outcome of its corresponding ast expr (`set_context('e')`).

Does that seem reasonable? This is related to #95, but I opened it as a new issue, in case `test_with` is doing something more than I'm anticipating.

**Comment by filipsch** [comment]
I don't see how 

```python
check_with().set_context('f', 'f2')
```

is necessary. The names `f` and `f2` should following from the `check_with()` automatically, and there should be robustness against using different names, if the student decides to and if the SCT writer wants to allow it (`same_names` argument or something).

I'd think more in terms of

```python
check_with().check_body().set_context(<value for f>, <value for f2>) # etc ...

check_for_loop().check_body().set_context(<value for iterator>) # etc ...

check_try_expect().check_handler('ValueError').set_context(<value for e>) # etc ...
```

What do you think?

**Comment by machow** [comment]
That's fair that `test_with` could set the context automatically. One challenge of setting it automatically within functions like `test_for_loop` is that the context needs to be set for some subtests, like `body`, but not others, like `comp_iter`, since this would break bad but valid cases like...

```{python}
i = 10
for i in range(i):
    print (i)
```

currently, `test_for_loop` tells only `body` and `orelse` to use context values, but the logic needs to be different with chaining. The situation occurs because `comp_iter` sits higher on the ast tree (it should be easy to work around). In this sense though, I think the syntax you laid out looks good, but it's important to think about whether these syntaxes would be equivalent...

```{python}
check_with().set_context(<value for f>, <value for f2>).check_body() # etc ...
check_with().check_body().set_context(<value for f>, <value for f2>) # etc ...
```

both are operations on state. It sounds like these two calls should produce equivalent results, and in a call to `set_context` should also happen automatically within `check_with`.

**Comment by filipsch** [comment]
I think the second one you mention makes most sense, because sometimes the context depends on which sub test you're going to test. (for example with the `test_try_except`). On the other hand, being able to set the context beforehand would be powerful: then you can reuse it for several subtests without having to re-initialize everytime.

_a call to set_context should also happen automatically within check_with._: Not sure about that. I think we really need to keep the difference between the most atomic steps, and then only think about easier to use functions that group some of these operations. The `check_` functions are atomic blocks, the `test_` functions are super-high level, and then we still need something in between, no?

**Comment by machow** [comment]
I realized that oftentimes tests didn't even need to set context vals from the opening statement of a with block, so implemented that piece separately as `with_context`. Like other functions, its body can be tested in combination with `with_context` (which performs like the original function), or  `set_context` (which lets you manually assign values to the target_vars). Commit c7b8f95dfee70

**Comment by machow** [comment]
was merged during giant spec pull request.
