### ISSUE TITLE
test_function mis-highlights lines

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#152]
Discussed with @hugo and @filipsch, test_function always highlights the first case where the function was used, which may be unrelated to the problematic line in a submission, either because the function wasn't used enough times, or because the person didn't mean to test the first case of using a function. Since bad highlighting is likely worse than no highlighting, it seems like we should remove highlighting for test_function.

Example, note the bad code is on line 11:

![image](https://cloud.githubusercontent.com/assets/2574498/20612440/e332ac20-b287-11e6-8000-d479d9e67624.png)

**Comment by filipsch** [comment]
removing highlighting for test_function seems like as step too far; it only can become problematic if there are several calls of the function under test, I'd say.

**Comment by machow** [comment]
@filipsch @hugobowne after making the changes, I realized that test_function implements a very reasonable strategy for highlighting--it just isn't documented.

test_function expects you to get highlighting right by doing the following

1. test that the function was used the right number of times (if it isn't, nothing will be highlighted). Use `test_function_v2(index=HIGHEST_INDEX)` or `test_function(index=HIGHEST_INDEX, args=[], keywords=[])`.
2. test the uses of the function in order, by setting index = 1, index = 2, etc.. If the first doesn't pass, it will fail and highlight the first use. If the first passes, but the second fails, it will highlight the second etc..

This can fail spectacularly when you don't expect people to use the function in the same order as the solution code. Remember that test_function looks at all cases, to see if it passes. Just in case, 

**I'm adding a highlight argument, which defaults to true, to test_function and test_function_v2.**

**Comment by filipsch** [comment]
@machow Ah, I thought you knew about that. It's all in the 'blacklisting' :)

**Comment by filipsch** [comment]
It's documented on the R side already [here](https://github.com/datacamp/testwhat/wiki/test_function#example-3-multiple-function-calls-2) (you already know that my style is rather verbose)

**Comment by machow** [comment]
This involves blacklisting, but is a separate issue, since if an SCT tests only one call, at index = 1, and the student leaves out the first function call, it will (confusingly) highlight the second.

**Comment by machow** [comment]
Disabled highlighting for now
