### ISSUE TITLE
one based indexing

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#157]
I wanted to open a discussion on one-based indexing, since the more I've thought about it, right now might be a critical time to make the switch to the True Path, 0-based indexing.

### Right now...

* test_* functions use 1-based indexing
* check_* functions use 0-based

### Pros and Cons

* **pro**: Keeping it this way could be very useful. For example `has_equal_value(expr_code="x[0]")` uses 0-based indexing.

* **con**: Having both in use at the same (transitional) time could definitely lead to confusion. 

Changing to 1-based now will only be a headache for the rest of our lives. I VOTE THE ONE TRUE PATH, 0-BASED INDEXING FOR CHECK FUNCTIONS.

(CC @hugobowne @filipsch @yrdatacamp)

**Comment by filipsch** [comment]
0ur future is 0-based!

**Comment by machow** [comment]
alright, nothing from Hugo or Yashas, so long live 0-based indexing ;)
