### ISSUE TITLE
test_dictionary()

### ISSUE THREAD

**Issue by vincentvankrunkelsven** [datacamp/pythonwhat#17]

**Comment by filipsch** [comment]
@vincentvankrunkelsven what use-cases did you have in mind? see if keys are correct, see if values are correct, some kind of type-specific `test_object()`?

**Comment by vincentvankrunkelsven** [comment]
Similar to `test_dataframe()`. See if all keys hold correct values. Also see if keys are correct (none are missing).

**Comment by filipsch** [comment]
Has been implemented and put live. 
Documentation will be added [here](https://github.com/datacamp/pythonwhat/wiki/test_dictionary)
