### ISSUE TITLE
Put Reporter instances on State rather than mutating global singleton

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#172]
Because a global Reporter object (`Reporter.active_reporter`) is used and mutated for testing, properties stored on it, like fallback highlighting, may spill over onto unrelated SCTs (#152).

Thoughts on changes:

1. Create `state.reporter`. `Ex()` could create a reporter instance to put on top level states.
2. Change references to `Reporter.active_reporter` to `state.reporter`. If there are cases where a reporter is used without access to state (unlikely), can use State.root_state.reporter.
3. Make a copy of reporter whenever it is accessed (i.e. state.reporter is a prop getter), in order to prevent the case where one sub-test affects another. (there is probably a better approach here).

The upside is that once the reporter global is gone, all the tests will be pure functions. The previous approach worked fine before, because a test and all it's subtests were executed in unbroken blocks, but the new spec clearly allows you to mix them up, e.g..

```
a = Ex().check_whatever()
b = Ex().check_something()

a.sub_test1()
b.sub_test2()
```

(in this sense, the change from v1 to v2 is like implementing threading on things that aren't thread safe)

**Comment by filipsch** [comment]
The architecture of pythonwhat has changed now, which relieves the need of a Reporter in the first place. The reporter does not 'hold' any information anymore. The reporter can just be a collection of reporting functions that you can call, and nothing more.

**Comment by machow** [comment]
@filipsch are these changes on a branch? It seems like the reporter on master still mutates state, so could cause side-effects across SCTs (for example, if you use a test_or, as test_function_v2 does).

https://github.com/datacamp/pythonwhat/blob/master/pythonwhat/Reporter.py#L42

**Comment by filipsch** [comment]
Changes are in master, thanks for flagging that I should double check.

**Comment by hermansje** [comment]
`active_reporter` doesn't exist anymore: it's refactored in #373
