### ISSUE TITLE
Correct submission throwing "Incorrect submission" -- block data June 23

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#18]
in the following exercise, when the actual solution is submitted, it is NOT accepted AND an”Incorrect submission” is thrown (screenshot below):

https://campus.datacamp.com/courses/1167/2627?ex=13

The same occurs in here and a few more: 

https://campus.datacamp.com/courses/1167/2627?ex=15

It's weird because there is not a problem in the following exercise and the SCT looks the same:

https://campus.datacamp.com/courses/1167/2627?ex=12

I think this is the SCT in question:

```
# Test: call to np.genfromtxt() and 'data' variable
test_correct(
    lambda: test_object("data"),
    lambda: test_function("numpy.genfromtxt")
)
```

<img width="1266" alt="screenshot 2016-06-08 12 34 29" src="https://cloud.githubusercontent.com/assets/4182382/15902340/6dc988b0-2d75-11e6-9472-8cd05f90b961.png">

All of this is currently on @franciscastro 's branch: https://github.com/datacamp/courses-importing-data-in-python/tree/review-francis

**Comment by vincentvankrunkelsven** [comment]
Problem is that `test_object()` uses `np.all()` in this case. If you test this code:
```
import numpy as np
file = 'titanic.csv'
data1 = np.genfromtxt( file1 , delimiter = ',', names = True , dtype = None )
data2 = np.genfromtxt( file1 , delimiter = ',', names = True , dtype = None )
np.all(data1==data2)
```
You'll notice that it results in `False`, even though the arrays seem exactly the same. This means `test_object()` will test false when it compares `data` from the solution environment with `data` in the student environment. The reason is because you have `numpy.float64` characters in the column with index `4`. This sometimes is `nan`, which is an object of the type `numpy.float64`. Apparently numpy doesn't count `nan == nan` as `True`. 

@filip we'll need a workaround for this. Maybe use `numpy.testing.assert_equal`.

**Comment by vincentvankrunkelsven** [comment]
Referencing this for fix: [http://stackoverflow.com/questions/10710328/comparing-numpy-arrays-containing-nan](http://stackoverflow.com/questions/10710328/comparing-numpy-arrays-containing-nan)

**Comment by hugobowne** [comment]
holy wacky races! spooky NumPy. The issue also occurs w/  dataframes FYI:

https://campus.datacamp.com/courses/1167/2627?ex=15

**Comment by hugobowne** [comment]
it also occurs with `pickle.load` when there are no NaNs. I can raise another issue if necessary. see screenshot


<img width="1264" alt="screenshot 2016-06-09 07 28 27" src="https://cloud.githubusercontent.com/assets/4182382/15928256/e1beb724-2e13-11e6-8c5d-0c2c7c71cff5.png">

https://campus.datacamp.com/courses/1167/2628?ex=3

**Comment by hugobowne** [comment]
same issue with `pd.ExcelFile()` 

https://campus.datacamp.com/courses/1167/2628?ex=4

in this case NOT dataframe but `type(xl) = pandas.io.excel.ExcelFile`

<img width="1260" alt="screenshot 2016-06-09 07 30 20" src="https://cloud.githubusercontent.com/assets/4182382/15928388/8e41ff88-2e14-11e6-804a-f78a0699e808.png">

**Comment by hugobowne** [comment]
Hi guys, this issue will block beta testing, which is slated for next Thursday 06/23. I'll need this to work before emailing potential beta testers, which I need to 4 days before beta testing starts (Sunday 06/19).

**Comment by hugobowne** [comment]
i checked out commit for this issue: will it work in the dataframe and excel cases?

see here:

https://campus.datacamp.com/courses/1167/2627?ex=15

and here:

https://campus.datacamp.com/courses/1167/2628?ex=4

**Comment by vincentvankrunkelsven** [comment]
Correct, this will do.

Note that this time I created specific equality tests for these kind of objects. If it's only used in just a few exercises and you can avoid it by using `do_eval = False` and `test_function()`, then do that. It's not manageable to create equality tests for all kinds of objects.

**Comment by hugobowne** [comment]
thanks!working in all cases except one:

https://campus.datacamp.com/courses/1167/2627?ex=13

<img width="1272" alt="screenshot 2016-06-18 14 40 20" src="https://cloud.githubusercontent.com/assets/4182382/16173006/c9839bc4-3562-11e6-91bc-5efb7f594dbc.png">


thoughts?

**Comment by vincentvankrunkelsven** [comment]
Use a workaround here (with `test_object(..., do_eval = False)` and `test_function(...)`). Use [this wiki section](https://github.com/datacamp/pythonwhat/wiki/test_object#object-equality) as a reference.

Btw, problem is that:
```
np.testing.assert_equal(np.genfromtxt(file , delimiter = ",", names = True , dtype = None), np.genfromtxt(file , delimiter = ",", names = True , dtype = None))
```
throws an `AssertionError`. Which means that even `np`'s testing framework doesn't see those numpy arrays as equal.
