### ISSUE TITLE
Changing default message of check_with -> check_context

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#188]
Currently is...

"Check your code in the first context of the first `with` statement. <FOLLOWUP STATEMENT>"

The problem is that few people see

```
with open('file1.txt') as f1, open('file2.txt') as f2:
    pass
```

and think of `open('file.txt')` as a "context", even if it produces a context manager.

@hugobowne thoughts on a better message? Something in the direction of "first piece of code in the head of the first `with` statement"? (but maybe less clunky ;).

**Comment by machow** [comment]
have pinged @hugobowne and others for feedback here and on slack with no response. Comment with suggestions to reopen.

**Comment by hugobowne** [comment]
i'm thinking about this! @yrdatacamp thoughts also welcome
