### ISSUE TITLE
pythonwhat too slow for many numpy exercises

### ISSUE THREAD

**Issue by filipsch** [datacamp/pythonwhat#189]
With the new react rewrite, we've enabled the 'report an issue' feature in campus to dump messages straight into Slack. A lot of issues are related to sessions being disconnected because the code took too long to execute. I've researched some of these cases, and _a lot_ of them are related to numpy and pandas (probably because it builds on top of numpy?)

As an example, go to [this exercise](https://campus.datacamp.com/courses/manipulating-dataframes-with-pandas/bringing-it-all-together?ex=14).

Insert this code into the editor (not that this code is not the same as the solution code, for the solution it runs fine):

```Python
# Create the DataFrame: usa
usa = medals.NOC=='USA'

# Group usa by ['Edition', 'Medal'] and aggregate over 'Athlete'
usa_medals_by_year = medals[usa].groupby(['Edition','Medal'])['Athlete'].count()

# Reshape usa_medals_by_year by unstacking
usa_medals_by_year = usa_medals_by_year.unstack(level='Medal')

# Plot the DataFrame usa_medals_by_year
usa_medals_by_year.plot()
plt.show()
```

- Case 1: Click submit answer: session disconnects.
- Case 2: Select the entire submit and hit Cmd + Enter (which sends it to console), it works fine.

The only difference between these two things is that pythonwhat's `test_exercise()` function is called in the first case.

If you check the eng-learn-events channel, you'll see that a lot of these 'it took too long to execute' complaints is because of exercises in 799 (intermediate python) and 1639 (pandas foundations). I'll ask people to give more examples about submissions that take too long to execute, so there's more information.

This issue severely affects user experience, so I'd look into this as you can.

**Comment by filipsch** [comment]
Issues keep pouring in about people using alternative solutions that take too long to be executed. I still suspect that this is due to the very inefficient dilling/undilling.

**Comment by machow** [comment]
We can make a quick fix to speed up uses of test_object (since it is guaranteed not to produce mutations, but I think the refactor handles this inefficiently).

The rest of the problem is likely caused by the use of large datasets, and pythonwhat's copying mechanism to protect against mutation in expression checks.
