### ISSUE TITLE
Testing an attribute (which is not a method) (fix date: July 1st)

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#19]
In [this exercise](https://campus.datacamp.com/courses/1167/2627?ex=16), we need to test line 7

```
data_array = data.values
```

and `test_function` doesn't work.

How do we test assigning attributes  to variables? :-)

<img width="1255" alt="screenshot 2016-06-08 12 39 29" src="https://cloud.githubusercontent.com/assets/4182382/15902477/1182a9fa-2d76-11e6-96e3-cb80bf6e3c04.png">

Tagging @franciscastro

**Comment by vincentvankrunkelsven** [comment]
`data.values` is not a function. Why don't you just `test_object(data_array)`? If you want to test the `values` column of `data` for some reason (I don't see why, but say you want to), you can use `test_data_frame()`.

**Comment by hugobowne** [comment]
You may have misunderstood: i want to test specifically that the student knows how to use attributes.

Neither `test_object(data_array)` nor `test_data_frame()` achieves this.  Just as `test_function` tests whether a function was used, I want to test whether a particular attribute of an object was called. I suppose some sort of analogue of a potential `test_attribute_called` . For a workaround, I could do some sort of funny regex business, I suppose.

does this make sense?

**Comment by filipsch** [comment]
@hugobowne we'll try to get this in production by July 1st.
For the time being, you can indeed do workaround with regexes. If you tell the student exactly how to name the object, this is pretty robust.

**Comment by filipsch** [comment]
We'll write a more general function: `test_object_accessed()`, that checks whether people use certain objects, or attributes in objects.

**Comment by hugobowne** [comment]
this is awesome! :-D
