### ISSUE TITLE
python backend not found

### ISSUE THREAD

**Issue by nadimmajed** [datacamp/pythonwhat#190]
Hello,
Can anybody help me plz, it is said here in order to run the test I need to install python backend, but i don't understand which package is python backend and how can I find it.

> Run tests
>  install python backend (private) + required packages
> sudo pip3 install boto3
> sudo pip3 install bs4
> sudo pip3 install h5py
> cd path/to/pythonbackend
> python3 setup.py install

thank you in advance.

**Comment by machow** [comment]
hey @nadimmajed, the python backend isn't a public package, but you can use pythonwhat to write exercises using Datacamp's [course creation platform](https://www.datacamp.com/teach/documentation#tab_getting_started). Happy to help if you run into any problems.

**Comment by nadimmajed** [comment]
Thank you for your answer.
