### ISSUE TITLE
Testing functions from package which was imported using aliasing

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#20]
if I `import numpy as np`, I need to `test_function("numpy.array",...)` for example, and change every message to say `np`, instead of `numpy`. 

Is it possible to have `test_function("np.array",...) ?

I checked out your work-around from Intro_python:

<img width="924" alt="screenshot 2016-06-08 12 44 23" src="https://cloud.githubusercontent.com/assets/4182382/15902715/5855585e-2d77-11e6-9fde-3049e8876f12.png">

**Comment by vincentvankrunkelsven** [comment]
It's not possible at the moment, if you want it you have to build your own message.

**Comment by filipsch** [comment]
@hugobowne To give some more context: It works now!

If you now use `test_function("numpy.array", ...)` (you still have to refer to the function with its full package name), `pythonwhat` will figure out under which alias the user used the `array()` function. If the user used `import numpy as np`, the automatically generated feedback messages will contain stuff like "inside your call of `np.array()`, argument x is incorrect".

Does this clarify things?

**Comment by hugobowne** [comment]
@filipsch this does clarify things greatly.

also, in these final remarks on issues raised on github, it would be helpful if you pointed to any change in documentation/wiki, if there is any, and if there is not, state explicitly that there is not. thanks
