### ISSUE TITLE
Numpy array testing, more flexible options

### ISSUE THREAD

**Issue by beangoben** [datacamp/pythonwhat#216]
Somewhat related to: `https://github.com/datacamp/pythonwhat/issues/206`, but not entirely.

**Context:**
Currently the equality testing is not flexible, especially if you are doing several math operations and each entry of a 1-d array depends on the previous, the order of operation can add numerical errors that get bigger across iterations/times leading to non equality. Here the suggestion to round the solution would not work.

**Feature request:**

Being able to define a function of two variables (student and solution) that will return a 1 if the correct and 0 if not, and use this as criteria for correctness.

This would allow for flexible grading, for example you could imagine a function that compares two signals and if the relative norm and cosine distance between these are within a certain threshold then they could be considered the same:

```
import numpy as np
from numpy.linalg import norm
from scipy.spatial.distance import cosine

def correct(x_sol,x_student):
     cond1 = 0.95 < norm(x_student)/norm(x_sol) < 1.05 # relative norm
     cond2 = cosine(x_sol,x_student) < 0.1
     return int(cond1 & cond2)
```

**Comment by machow** [comment]
> the order of operation can add numerical errors that get bigger across iterations/times leading to non equality

At which point it sounds like an SCT should fail. To reopen, please provide a concrete, realistic exercise in which element-wise rounding, or a tolerance argument to `allclose` would be insufficient.

**Comment by beangoben** [comment]
I think with the implementation of `allclose` many of the numerical accuracy issues could be solved.

Still, from a educational point of view I think being able to use more flexible forms of grading that do not depend on one variable transformations (np.shape, np.round, etc) and equivalence testing increases the potential of more interesting problem prompts.

For example, you could ask, **construct a 2-D vector linearly independent from [0,1]**

The solution space is 1 dimensional ([a,0]), for which you would could test `np.dot(v_student, v_sol) < 1e-10` with `v_sol = np.array([0,1])`. You could easily complicate this exercise to make it more complex than just a 1-d solution space. If you make extend this to a 100-dimensional space, it does not make so much sense to encode the reference vector into the testing, for which "pulling" the variable from the solution space is cleaner.

Or for a more complicated prompt, which could be used for the course I am currently maintaining would be, **construct a wavefunction that can tunnel through the given barrier", instead of constructing one solution, the problem accepts multiple solutions.

Or the previous example I gave, gives a flexible criteria for comparing 1-D signals or 2-D arrays as similar, without having to be numerically equal.

**Comment by machow** [comment]
Those are fair points--it should be a pretty simple to implement. When I implement `allclose`, I'll make it so that people can specify their own equality checking functions.
