### ISSUE TITLE
test_numpyarray function

### ISSUE THREAD

**Issue by beangoben** [datacamp/pythonwhat#217]
**Feature request:**

Having a test function catered to 1-D, 2-D numpy arrays, in particular that could check:

- If defined (already implemented)
- Have the same datatype (i,g list vs np.array)
- Have the same shape (i.g (2,3) vs (3,2))
- Has the same contents, or very close (like numpy's allclose `https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.testing.assert_allclose.html`), equality is only implemented

Currently if I wanted to do this I have to do the following test:

```
key = 'y'
# messages
type_msg="__JINJA__: **type** **mismatch**: expected `{{sol_eval}}`, got `{{stu_eval}}`."
type_expr = 'type({:s})'.format(key)
shape_msg="__JINJA__: **shape** **mismatch**: expected `{{sol_eval}}`, got `{{stu_eval}}`."
shape_expr = '{:s}.shape'.format(key)
contents_msg="__JINJA__: **solution** **contents** are different, expected `{{sol_eval}}`, got `{{stu_eval}}`."

Ex().check_object(key)  \
    .has_equal_value(expr_code = type_expr,incorrect_msg=type_msg)  \
    .has_equal_value(expr_code = shape_expr,incorrect_msg=shape_msg) \
    .has_equal_value(incorrect_msg=contents_msg)
```

Would nice to have a function that could wrap around all these scenarios such as 
```
test_numpyarray(key,type_test=True,type_msg,shape_test=True,shape_msg,content_test='allclose', contents_msg)
```

**Comment by machow** [comment]
Hey @beangoben, thanks for the suggestions. To be sure, it sounds like for the most part the behavior you're looking for can already be done, so the feature you are requesting is largely not having to repeat yourself. For context, our current thinking is that feature requests that fall under "I don't want to repeat myself" should be implemented by letting content developers maintain a separate package of high-level SCTs that they find personally useful (cc @filipsch ). Some specific responses below.

> having same datatype

See the SCT (specifically `is_instance`) [here](https://datacamp.github.io/courses-pythonwhat-tutorial/#int)

> have the same shape

We are not going to make a special function to test a specific attribute of an object, such as `x.shape`, with a custom message. But I understand that having to rewrite a message for every exercise throughout a course isn't DRY, which is why we want to let people maintain a separate high-level SCT library.

> Has the same contents, or very close

I've been thinking about `allclose`, and it seems like a nice addition! I'll try to implement it when I take a pass at fixing the equality tests ( #215 ). Opened an issue here: #218

**Comment by beangoben** [comment]
Got it, so then the suggested route is creating a module of high level routines based on personal preferences right? 

Is there an example of how to integrate this easily with Datacamp?
As I understand it the solution seems cumbersome, since you have to make a pip installable module, add it to your requirements.sh and export it in each SCT.

In a easy to use case, I would imagine you could attach a python file to a project with your favorite test snippets and that you could call these snippets automatically..in the same way that you can already use `Ex()` in the sct enviroment.

Thanks for the response!

**Comment by machow** [comment]
Yeah--you hit on the two options we were thinking of.

> As I understand it the solution seems cumbersome, since you have to make a pip installable module, add it to your requirements.sh and export it in each SCT.

This is the route we've been  leaning toward, and in this case we would set up a default pythonwhat-ext library, and automatically import its SCTs before the SCT block code is run.

> In a easy to use case, I would imagine you could attach a python file to a project

we implemented something like this for `sqlwhat`, but never merged it. I was a bit concerned that the code would be difficult to test.

Definitely interested to get your take on which is better. I built a basic extension library for sqlwhat, but haven't made it so the backend automatically loads the SCTs. Example [here](https://github.com/datacamp/sqlwhat-ext/blob/master/sqlwhat_ext.py).

**Comment by beangoben** [comment]
My preferences would be towards the `sqlwhat`, mostly for ease of use, making a pip installable python mini-module is easy...but I could see how that might be a turnoff for somebody that has never done it before (think a professor making a course). If you want people to have a happy experience on content creation on Datacamp, I think this might be easier..but this is me speaking without knowing how the testing side would be.

Hope it helps,

**Comment by machow** [comment]
Super helpful to hear! That's a good point that it would raise the bar for people who aren't used to packaging / don't write a lot of SCTs. The upside seems like packaging encourages documentation, testing, and code reuse (but moves more slowly).

I'll have to think more about the uploading a script approach more. It might be something worth implementing after people get the hang of packaging their own SCTs.

**Comment by filipsch** [comment]
I would reduce as much as possible the coding and obscurity on our side before we decide to dedicate more resources into a custom way to provide python scripts in the course container etc.
This would affect multiple applications, while simply creating a separate package and installing it in `requirements.sh` is already possible out of the box...

**Comment by machow** [comment]
@beangoben I set up `pythonwhat-ext`, with a simplified version of `check_numpy_array`. Going to close this issue and open one for fleshing out `check_nump_array` there. Alternatively, you could fork that repo, and then just use the forked version in your course! cc @yrdatacamp
