### ISSUE TITLE
Allow equality checks to use numpy's `allclose`

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#218]
This should be opt in. Maybe, `has_equal_value(func = np.allclose)` or something similar? On the other hand, it seems like allowing arbitrary equality functions could lead to crazy (and surprising) behaviors. In that case, it could be something like `has_equal_value(tol = 2)`

**Comment by filipsch** [comment]
+1 for the tolerance option.

**Comment by machow** [comment]
after discussion on #216 I agree with @beangoben that allowing people to specify equality testing functions would be useful. It seems like we should just be clear with the content development team that they shouldn't go wild with it :).

**Comment by machow** [comment]
in production in v2.8.0!
