### ISSUE TITLE
add copy arguments to test_function and friends

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#219]
This will allow people to fix cases where copying has lead to slow SCTs in old exercises. cc @yrdatacamp

**Comment by machow** [comment]
@filipsch I suspect that it's ready to go, but the validator failed for a couple exercises:

https://ci.datacamp.com/view/LE%20Docker/job/Docker%20Python%20Shared/17/console

I didn't have time to check out why (maybe just simple timeouts?). If they don't seem problematic, seems good to merge.

**Comment by filipsch** [comment]
@machow the output log includes a link with the exercises that failed. I tested some of them (by adding the `shared_image=...` query parameter to the campus app link, and they worked fine, so I'm activating.
@yrdatacamp I'm closing this; do you know enough to fix slow SCTs?
