### ISSUE TITLE
Test if function arguments are there

### ISSUE THREAD

**Issue by vincentvankrunkelsven** [datacamp/pythonwhat#22]
It's not possible to test whether arguments in a function are used, without checking whether they have the correct value (evaluated or un-evaluated)

**Comment by filipsch** [comment]
It's on `development` branch; you can check arguments without checking their evaluated version or string version by setting `do_eval` to `None`.

**Comment by filipsch** [comment]
Information is available in the wiki as well:
https://github.com/datacamp/pythonwhat/wiki/test_function#do_eval

**Comment by filipsch** [comment]
Available on production now.
