### ISSUE TITLE
check_function_def + expr code not working

### ISSUE THREAD

**Issue by beangoben** [datacamp/pythonwhat#221]
Using expr_code for rounding floats when checking function definitions does not work.
Student:
```
def one_val(x):
    val=1
    return val-0.000001
```
Solution:
```
def one_val(x):
    val=1
    return val
```
Error checking code:
```
import numpy
Ex().check_function_def('one_val').call([0.0]).has_equal_value(expr_code='np.round(a,decimals=4)')
```
Which will raise the following error:
_Incorrect submission
Check your code in the definition of one_val(). Calling it should result in 1, instead got 0.999999_

**Comment by machow** [comment]
Good point--there is a boundary problem around whole numbers using a simple `round` approach. A tolerance parameter would round the difference of two numbers, which removes the issue. This will be resolved once #218 is implemented.

Are there exercises that are currently broken by this limitation? When do they need to be not broken by? cc @hugobowne @yrdatacamp

**Comment by beangoben** [comment]
Now if possible, we are one week into a online course with 5k+ students, where numerical error can be very unforgiving. We are using numerical rounding  (`np.round(x,4)`) as a work around for `np`closeall`  and so the lack of the same testing for functions leads to an uneven experience and frustration.

**Comment by machow** [comment]
@beangoben I mistakenly thought you were a new DataCamp intern! Okay--it sounds like this is for an open course? 5k+ students is an incredible number. What course is it? I'll try to take a quick pass at fixing this issue while implementing the `pythonwhat-ext` library.

**Comment by beangoben** [comment]
@machow jaja no problem, yeah it's for [QuantumWorldX](https://www.datacamp.com/courses/2435). Exciting news about the pythonwhat-ext library.

**Comment by beangoben** [comment]
@machow hi wanted to ask what the expect timeline was for this bug? I have some students to reply to about getting stuff like "Calling square_component(0.5, 2, 3) should result in -3.11853746602e-16, instead got -3.11853746602e-16." (a mismatch at the 13th digit) and want to give them an estimate.

By the way pythonwhat-ext is a great feature, just deployed my own [qwxwhat](https://github.com/beangoben/qwxwhat)

**Comment by machow** [comment]
Ah, glad to see the extension package was useful! I don't think I can put an `allclose` feature into production in the next few days. However, I can make a branch on pythonwhat with a first pass on the implementation, if you want to use that in the QuantamWorldX course. I can also open a PR on qwxwhat with an SCT function called `has_allclose_value` (or something), so if I end up making changes before putting on the production version of pythowhat, we'll just need to tweak `has_allclose_value`.

(I'm guessing the first pass won't change much)

**Comment by beangoben** [comment]
A PR would work, and then I can just modify it once the functionality  gets rolled out. Thanks a lot.

**Comment by machow** [comment]
@beangoben I implemented a fix and pushed it into production. Example here: https://datacamp.github.io/courses-pythonwhat-tutorial/testing-objects.html#custom-equality-test

Thanks for all your feedback!
