### ISSUE TITLE
Order of testing incorrect (test_function_definition + test_object )

### ISSUE THREAD

**Issue by beangoben** [datacamp/pythonwhat#222]
I believe I found an error, when using `test_function_defnition' and 'Ex().test_object()' the order of operation is not respected. This can be quite problematic since the value of the object depends on the function and if the function is incorrect you will get an error message on the object but not the function.
I need to use 'Ex().test_object()...' because I need to round numbers and check array shapes.
If this is indeed an error is can be quite serious and frustrating for students in a online course since the feedback does not provide any information.

Student code (difference is in `func_add`)
```
import numpy as np
def func_add(x,i):
    return x +i - 0.001
x = np.arange(0,5)
y = np.zeros((10,len(x)))
for i in range(len(y)):
    y[i,:] = func_add(x,i)
```
Solution code:
```
import numpy as np
def func_add(x,i):
    return x +i
x = np.arange(0,5)
y = np.zeros((10,len(x)))
for i in range(len(y)):
    y[i,:] = func_add(x,i)
```
Sct code:
```
test_function_definition('func_add', arg_names = False, arg_defaults = False, # Already tested this
    results = [ [5, 2.0],[0.35,1.0]])
Ex().test_object('y')
```

**Comment by filipsch** [comment]
Hey @beangoben thanks for raising this. Things get tricky if you combine the 'old' way of doing things (using very monolithic `test_` functions) with the new way of doing things (using the chaining, starting with `Ex()`). In this case, the `test_` functions will indeed be executed in the end.

Can you try to rewrite your `test_function_definition()` function to use `Ex().check_fun_def()`? It's documented [here](http://pythonwhat.readthedocs.io/en/latest/part_checks.html#function-definition-lambda-args). Let me know if it worked.

**Comment by beangoben** [comment]
hi @filipsch , thanks I did look at it, but had problems with the outputting of error messages (#223) when using call along with `check_fun_def`...was hard to find a way of printing dynamically things that `test_function_definition` does well such a : number of arguments, a missing argument, test call of functions with specific arguments and incorrect results. Unless i am mistaken It seemed there was no easy way of controlling these messages.

**Comment by filipsch** [comment]
@beangoben I have to refer to @machow for that one.
If you want to keep using `test_function_definition()`, you can also remove the `Ex().` from `Ex().test_object()`. This should also fix the order.

**Comment by machow** [comment]
@beangoben you can put `Ex()` before any of the SCTs, so 

```
Ex().test_function_definition('func_add', arg_names = False, arg_defaults = False, # Already tested this
    results = [ [5, 2.0],[0.35,1.0]])
Ex().test_object('y')
```

should run `test_function_definition`, followed by `test_object`. I tested it quickly by adding `Ex().test_function_definition('shout')` to [this example](https://datacamp.github.io/courses-pythonwhat-tutorial/user-defined-functions.html#functions-with-multiple-parameters), and it appeared to work. Def reopen if it doesn't solve your problem.
