### ISSUE TITLE
success_msg hangs exercise

### ISSUE THREAD

**Issue by beangoben** [datacamp/pythonwhat#224]
Adding this message to the sct tester will leave the session on datacamp hanging until time out.
This is irrespective of code. 
Should be documented if utf-8 strings are going to breaks tests.

*** =sct
```{python}
success_msg("Schrödinger conqueror")
```

**Comment by filipsch** [comment]
Should be fixed when I deploy a new image for python; stay tuned.

**Comment by filipsch** [comment]
If you did not specify a custom `from:` option in the `course.yml` file, it should be fixed.
