### ISSUE TITLE
best way to test pythonwhat-ext before deployment?

### ISSUE THREAD

**Issue by beangoben** [datacamp/pythonwhat#231]
What is the best way to test pythonwhat-extensions? (which are really helpful by the way)
I currently update the git, tag it with some version, update the requirements.sh in the course and then I wait 20 minutes for the image + test all chapters.
If i have an error in the extensions...I have go back and do this flow again....if these an easier/faster way to do ? (testing on a local computer?) Is there docs on testing these extentions on the fly?

**Comment by machow** [comment]
My sense is that there are two good approaches:

### 1. In the teach editor
While working on an exercise in the teach editor, copy the extension function into the SCT block. After modifying it, and verifying it works, copy the changes back into your ext repo. For example...

```
@state_dec
def check_numpy_array(name, state = None):
    """Test a numpy array object. Return that object.
     
    Args:
    name: name of the object to be tested.
     
    """
    # is defined
    obj = Ex(state).check_object(name)
     
    # is a numpy array
    obj.is_instance(np.ndarray)

    # etc...


# then use for exercise

Ex().check_numpy_array('x')
```

### 2. Testing locally

See the [tests in pythonwhat-ext](https://github.com/datacamp/pythonwhat-ext/blob/master/tests/test_check_numpy_array.py) for details, these can run locally, and the repo is using travis-ci to run tests whenever a change is made. I set up a mock process in `helpers.py` to let the tests run locally. There are some limitations here, for example if you import a library in the student code, it will import it in the solution code.

(I should pull `helpers.py` into `pythonwhat` at some point!)
