### ISSUE TITLE
test_not + test_student_typed function in pythonwhat-ext

### ISSUE THREAD

**Issue by beangoben** [datacamp/pythonwhat#232]
I am trying to write a function `check_testfunction_call` that will check that students do not type a particular function `name` (i.g. `test_function1`) into their solution, this function is part of a pythonwhat-ext: [qwxwhat](https://github.com/beangoben/qwxwhat).

For this i am using `test_not` and `test_student_typed`. I am having trouble implementing it since I keep getting an error when running a test: `test failed with backend-error: 'NoneType' object has no attribute 'student_code'`

I know test_student_typed works...but it seems using it with test_not is what breaks it.

My current function looks like this:
```
from pythonwhat.check_syntax import state_dec, Ex
from pythonwhat.test_funcs import test_student_typed
from pythonwhat.check_funcs import test_not

@state_dec
def check_testfunction_call(name, state=None):
    obj = Ex(state).test_not(test_student_typed(
        "{:s}\s*\(".format(name)), msg=CHEAT_MSG.format(name))

    return obj
```

**Comment by machow** [comment]
hmm.. I'm not sure what's going on. I was able to get it to work...

```
from pythonwhat.check_syntax import state_dec

@state_dec
def check_testfunction_call(state=None):
    obj = Ex(state).test_not(test_student_typed('SOMETHING'), msg = "FAILED")

    return obj

Ex() >> check_testfunction_call()
```

If the student code has the string "SOMETHING" I see the failure message. (I just pasted it in to the interactive docs [here](https://datacamp.github.io/courses-pythonwhat-tutorial/#Running-a-simple-test)).

Do you mind verifying that works, and then adapting to see if you can recreate the error?

**Comment by machow** [comment]
I put a note in the pythonwhat-ext source, explaining that SCTs should be imported from pythonwhat.sct_syntax, feel free to reopen if the issue is still there

**Comment by beangoben** [comment]
@machow, I tried it out and it does not work for me.

This is my current setup:
**qwxwhat_ext.py**
```python
@state_dec
from pythonwhat.check_syntax import state_dec, Ex
def check_testfunction_call2(state=None):
    obj = Ex(state).test_not(test_student_typed('SOMETHING'), msg = "FAILED")
    return obj
```
**solution**
```python
from qwxwhat import check_testfunction_call2

Ex() >> check_testfunction_call2()
```
And I get `test_student_typed` is not defined error.

If import from `pythonwhat.test_funcs` and `pythonwhat.check_funcs`, I get a different error: '`'NoneType' object has no attribute 'student_code'
