### ISSUE TITLE
add check_class_def

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#233]
cc @hugobowne 

To test cases like...

```
class A(object):
    def __init__(self): pass
```

Here is the AST. Note that the body of the class is just python expressions, so we would only need to add an SCT to select the ClassDef node (and maybe to grab the bases).

![image](https://user-images.githubusercontent.com/2574498/28372534-fb7c0b6e-6c6d-11e7-9b23-e32531f8018e.png)

**Comment by machow** [comment]
@gvwilson I'll walk through this on Friday morning. Below are details for how to implement a `check_class_def` SCT.

## Useful lines of code

* [while parser](https://github.com/datacamp/pythonwhat/blob/master/pythonwhat/parsing.py#L540) - fairly similar to what's needed here.
* [check_node SCT](https://github.com/datacamp/pythonwhat/blob/master/pythonwhat/check_funcs.py#L66) - used behind the scenes to grab while AST nodes
* [wrapping check_node to create check_while](https://github.com/datacamp/pythonwhat/blob/master/pythonwhat/check_wrappers.py#L56)

## Steps to implement

Add a parsing class to `pythonwhat.parsing.py`, that looks something like...

```python
class ClassDefParser(Parser):
    """Find class def structures.
    A parser which inherits from the basic parser to find class def structures.
    Only 'top-level' class def structures will be found!
    """

    def __init__(self):
        self.out = []

    def visit_ClassDef(self, node):
        self.out.append({
            'node': node,
            'name': "name": getattr(node, 'name', None),
            'bases': [{'node': base} for base in node.bases],
            'body': node.body,
            })
```

Update [`pythonwhat/check_wrappers.py` here](https://github.com/datacamp/pythonwhat/blob/master/pythonwhat/check_wrappers.py#L27) with something like ```'class_def': 'class definition of `{index}`'```

Update [`pythonwhat/check_wrappers.py` here](https://github.com/datacamp/pythonwhat/blob/master/pythonwhat/check_wrappers.py#L21) with `'bases': '{ordinal} base class'`

Update the parses dict in [`pythonwhat/parsing.py](https://github.com/datacamp/pythonwhat/blob/master/pythonwhat/parsing.py#L825). This is used by [`pythonwhat/state.py` here](https://github.com/datacamp/pythonwhat/blob/master/pythonwhat/State.py#L303) to put property methods on the `State` class for each parser.

**Comment by filipsch** [comment]
@machow has this also been coded up at some point?

**Comment by machow** [comment]
@filipsch I don't think so, the other parsing related issue that was never implemented is async functions 

https://github.com/datacamp/pythonwhat/issues/210
