### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by pulkitpahwa** [datacamp/pythonwhat#235]
Can you please mention the LICENSE structure of the project ?

Are we free to use it in our project ?

**Comment by machow** [comment]
Hey @pulkitpahwa, let me check over the next couple days on licenses and get back to you!

**Comment by karambir** [comment]
Hey @machow 

Is there any update on this issue? I may use this into one of my project but can't before it is properly licensed.

Thanks for the project though :+1:

**Comment by machow** [comment]
Thanks for raising this again. Will do it this afternoon :)

**Comment by machow** [comment]
I've added the AGPL V3 copyleft license. Happy to answer any questions.

**Comment by karambir** [comment]
@machow Thank you. Maybe you can do explicit licensing in [testwhat](https://github.com/datacamp/testwhat) and [protowhat](https://github.com/datacamp/protowhat/) as well :)

**Comment by machow** [comment]
@karambir updated both licenses, definitely feel free to open an issue if you need help with anything (or want to show anything off :).
