### ISSUE TITLE
Grader issue intro to Python edx?

### ISSUE THREAD

**Issue by martijnsublime** [datacamp/pythonwhat#244]
@filipsch given your new role, I assume I can tag you on this. I received two emails by edx regarding intro to python

- https://www.dropbox.com/s/bi54rbmk5u39kll/Screenshot%202018-04-16%2018.52.00.png?dl=0
- https://www.dropbox.com/s/18hsfcnfw3cytsq/Screenshot%202018-04-16%2018.52.15.png?dl=0 

Could you let me know if these are actual issues or if not? I need to get back to them

**Comment by filipsch** [comment]
- First screenshot: this is a content problem; the SCT is not properly written (see [here](https://github.com/datacamp/courses-intro-to-python-edx-final-lab/blob/master/chapter1.md#L128)). Should not use `has_equal_ast` so it can allow for multiple arguments, for example by checking on the output immediately.
- Second screenshot: this is a content problem; the SCT is not properly written (see [here](https://github.com/datacamp/courses-intro-to-python-edx-final-lab/blob/master/chapter1.md#L299)). Should not use `test_function.head()` if other functions should be accepted as well.

Closing here and moving it to https://github.com/datacamp/courses-intro-to-python-edx-final-lab.

For future issues, I suggest you create the issue on the related course itself, after which the person responsible for maintenance can bump it up if it's an actual issue (I will draft communication guidelines soon to make this clear for everybody and update github issue templates accordingly after checking with nick).

**Comment by filipsch** [comment]
Issue moved to [datacamp/courses-intro-to-python-edx-final-lab #11](https://github.com/datacamp/courses-intro-to-python-edx-final-lab/issues/11) via [**ZenHub**](https://www.zenhub.com/)
