### ISSUE TITLE
Switch from unittest to pytest entirely + clean up test infrastructure

### ISSUE THREAD

**Issue by filipsch** [datacamp/pythonwhat#246]
- Get rid of `unittest`
- Properly use fixtures everywhere instead of `setUp` and `tearDown` classes. `sqlwhat` boasts some good examples of this. 
- Fix structure so it's according to industry standards
- Verify that description of how to run tests locally (in README) is very similar to what travis does.

**Comment by filipsch** [comment]
As @machow suggested in a comment in #254, we should use the `pytest.mark.parametrize` decorator extensively to reduce the insane duplication in unit tests:

_Totally unnecessary suggestion here, but with pytest, you can remove much of the duplication with_

```
@pytest.mark.parametrize('s', [
    "x = 4 + 5 - 7 + 7 * (8) / 9",     # assignment
    "(12, 23)",                        # tuple1,
    "(12, )"                           # etc..
    ])
test_parses_without_errors(s):
    State.parse_internal(s)
```

_here's an example from sqlwhat: https://github.com/datacamp/sqlwhat/blob/master/tests/test_basic.py#L46-L79_

**Comment by machow** [comment]
In case it's useful, here's an example of how pytest sets up and cleans up tests:

https://github.com/datacamp/sqlbackend/blob/0306c5b27e6df28e215278222fea487e71c9521d/sqlbackend/tests/test_exercise.py#L6-L14

It uses a generator, where everything up to the yield statement is setup, and everything after is teardown.
