### ISSUE TITLE
test_correct not working on sql_achemy function

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#25]
https://campus.datacamp.com/courses/1167/2629?ex=4

SCT is currently this:

```
# Test: call to create_engine() and 'engine' variable
test_correct(
    lambda: test_object("engine"),
    lambda: test_function("sqlalchemy.create_engine")
)
```
see screenshot for error:

<img width="1277" alt="screenshot 2016-06-14 14 05 05" src="https://cloud.githubusercontent.com/assets/4182382/16054028/59161474-3239-11e6-872d-0141c2bb4190.png">

could it be a ploblem with importing like this?

`from sqlalchemy import create_engine`

this is a standard import so a workaround would be great.

this issue will block beta testing. please all feel free to suggest workarounds!

**Comment by hugobowne** [comment]
i have what looks like an analogous issue here:

https://campus.datacamp.com/courses/1167/2630?ex=6

<img width="1268" alt="screenshot 2016-06-14 14 30 48" src="https://cloud.githubusercontent.com/assets/4182382/16054784/b1164934-323c-11e6-9b3c-b8f9f8c4829b.png">

**Comment by vincentvankrunkelsven** [comment]
(note to self) Maybe related to #24

**Comment by vincentvankrunkelsven** [comment]
Same story, objects are not equal. Use `do_eval` like you did in #23. 
```
test_object("engine", do_eval = False)
test_function("sqlalchemy.create_engine")
```

**Comment by vincentvankrunkelsven** [comment]
Use 
```
test_object("engine", do_eval = False)
test_function("create_engine")
```
Same problem as #23 + you should use `"create_engine"`, you're not using the package in the code either.

Same for your other problem, don't use the packages if you don't use them in the code.

**Comment by hugobowne** [comment]
gr8 thx!
