### ISSUE TITLE
Solution not accepted with test_correct for engine connection

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#26]
https://campus.datacamp.com/courses/1167/2629?ex=7

<img width="1276" alt="screenshot 2016-06-14 14 18 04" src="https://cloud.githubusercontent.com/assets/4182382/16054480/5e6ba78e-323b-11e6-869c-177f4fe67b0b.png">

this issue will block beta testing. please all feel free to suggest workarounds!

**Comment by hugobowne** [comment]
there's a potentially related issue in the next exercise:

https://campus.datacamp.com/courses/1167/2629?ex=8

<img width="1267" alt="screenshot 2016-06-14 14 23 16" src="https://cloud.githubusercontent.com/assets/4182382/16054537/9fefb86c-323b-11e6-873d-9e7dedf2a2a2.png">

**Comment by vincentvankrunkelsven** [comment]
for `con` and `rs` use:
```
test_object("con", do_eval = False)
test_function("engine.connect")
```
and
```
test_object("rs", do_eval = False)
test_function("con.execute")
```
Instead of the `test_correct`s. Objects are not same, not worth it to build specific equality check.
