### ISSUE TITLE
Test_correct error on solution: pandas.read_sql_query

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#27]
https://campus.datacamp.com/courses/1167/2629?ex=16

<img width="1274" alt="screenshot 2016-06-14 14 24 47" src="https://cloud.githubusercontent.com/assets/4182382/16054687/3fe8f7f2-323c-11e6-9304-89f80cf95dd6.png">

this issue will block beta testing. please all feel free to suggest workarounds! i could just test_object, if necessary?

**Comment by vincentvankrunkelsven** [comment]
```

**Comment by hugobowne** [comment]
works, thx!
