### ISSUE TITLE
Write SCTs for chapter 1 and 2 of "Analyzing Police Activity with pandas"

### ISSUE THREAD

**Issue by beccarobins** [datacamp/pythonwhat#285]
@filipsch @yashasroy 

As discussed (separately) Filip will write SCTs for a couple chapters of this course to get familiar with SCTs when dealing with pandas. I'll have you work in the `filip_scts` branch and make a small request that once finished, one of you issue and merge the PR. Here are the [Teach](https://www.datacamp.com/teach/repositories/1497/branches/filip_scts) and [GitHub](https://github.com//datacamp/courses-analyzing-police-activity-with-pandas/tree/filip_scts) links.

**Comment by filipsch** [comment]
@beccarobins what's the deadline for this?

**Comment by beccarobins** [comment]
@filipsch 

June 25th. That should give either Eukung or me enough time to get through the last two chapters of SCTs and hopefully we can launch it that Friday.
