### ISSUE TITLE
test_or() doesn't work in combination with test_correct()

### ISSUE THREAD

**Issue by sumedh10** [datacamp/pythonwhat#288]
`test_or()` and `test_correc()` work fine by themselves, but not in combination with each other. 

### Pre-exercise code

```{python}
import pandas as pd
import seaborn as sns

tips = sns.load_dataset('tips')
```

### Solution

`@solution`

```{python}
import matplotlib.pyplot as plt

# Bar plot
cts = tips.sex.value_counts()
cts.plot(kind='bar')
plt.show()
```

### SCT 1
```{python}
Ex().test_correct(
    check_object("cts").has_equal_value(), 
    test_or(
        check_function("tips.sex.value_counts"), 
        has_equal_ast("", "tips['sex'].value_counts()", exact = False)
    )
)
```

### SCT 2

```{python}

Ex().test_or(
        check_function("tips.sex.value_counts"),
        has_equal_ast("", "tips['sex'].value_counts()", exact = False)
)

Ex().check_object("cts").has_equal_value()
```

SCT 2 passes, but SCT 1 fails with the following error: 

<img width="766" alt="screenshot 2018-06-19 10 59 59" src="https://user-images.githubusercontent.com/8866417/41605695-f326dad0-73af-11e8-9fd0-de883c9578b2.png">

**Comment by machow** [comment]
@filipsch I took a quick look earlier, and have a sort of loose sense what might be going on. Happy to pair whenever you take a pass at this.
