### ISSUE TITLE
Get rid of __JINJA__ prefix

### ISSUE THREAD

**Issue by filipsch** [datacamp/pythonwhat#299]
Put simply, Jinja should be the only templating method. In that case,  `'__JINJA__:'` can just be removed from a string if present and _every_ string can be rendered as a Jinja template. This relieves CDs from having to write `__JINJA__:` in front of every message that wants to use template variables that have been programmatically generated during execution.

**Comment by machow** [comment]
@filipsch I think the __JINJA__ part is just for messages that had to include logic (conditionals, etc..). For strings of the form "Your {some_part} of your {some_other_thing} was wrong", most of those use regular string formatting.

From what I remember, I used Jinja to preserve some complex messages that existed around testing data frame columns.

**Comment by filipsch** [comment]
@machow I'm not sure if you understood my message. I want to keep Jinja, I just want to make it the standard. When leveraged smartly, JINJA can even be used by CDs to programmatically build messages depending on what the student did wrong.

**Comment by machow** [comment]
@filipsch that makes sense. As I recall, there weren't a lot of cases where I felt a need to use JINJA with pythonwhat messages, so string formatting might get people a long way. (But the idea of using JINJA by default is admittedly pretty intriguing)
