### ISSUE TITLE
Correct submission throwing `'predef_msg' is not defined` error: block date June 23

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#30]
https://campus.datacamp.com/courses/1167/2629?ex=12

<img width="1273" alt="screenshot 2016-06-18 14 42 45" src="https://cloud.githubusercontent.com/assets/4182382/16173015/113d8254-3563-11e6-8ea8-3314ac623a53.png">

**Comment by vincentvankrunkelsven** [comment]
```
predef_msg = "You don't have to change any of the predefined code."
test_with(
    1,
    context_vals = True,
    context_tests = lambda: test_function("engine.connect", not_called_msg = predef_msg, incorrect_msg = predef_msg),
    body = test_with_body
)
```
is errorneous. `predef_msg` is not defined inside the scope of the lambda expression.
Hacky workaround if you want to use lambda expression:
```
...  context_tests = lambda(predef_msg=predef_msg): test_function("engine.connect", not_called_msg = predef_msg, incorrect_msg = predef_msg) ...
```
