### ISSUE TITLE
Overall look at "Manipulating Time Series Data with Python" ch4ex3

### ISSUE THREAD

**Issue by klmedeiros** [datacamp/pythonwhat#306]
Here's the issue on this particular exercise for reference: https://github.com/datacamp/courses-manipulating-time-series-data-python/issues/21

The provided solution asks for:
```
# Print company name, market cap, and last price for each component 
info_cols = ['Company Name', 'Market Capitalization', 'Last Sale']
print(listings.loc[tickers, info_cols].sort_values('Market Capitalization', ascending=False))
```

However, as noted in the issue, you can print the same thing if you use the following code:
```
info_cols = listings.loc[tickers,['Company Name','Market Capitalization','Last Sale']]
print(info_cols.sort_values(by='Market Capitalization',ascending=False))
```

The entire exercise needs to be converted to `check_*` syntax, plus I'm having trouble nailing down 100% how to do the `test_or()`s here. I have some code that's commented out, but it's just confusing me more than anything else. If you could take a look, that would be great.

Thanks, and let me know if you need more info from me.

**Comment by filipsch** [comment]
@klmedeiros did you already do any work on this on a branch? If yes, please refer it here as well.

**Comment by klmedeiros** [comment]
@filipsch I've worked on this exercise on the SCTs branch of the course here (https://www.datacamp.com/teach/repositories/1130/branches/SCTs); you can see some of it in the PR request I sent you for this course (datacamp/courses-manipulating-time-series-data-python#42)

**Comment by filipsch** [comment]
Done in [this commit](https://github.com/datacamp/courses-manipulating-time-series-data-python/commit/7e40eb4b72a5a638c51fca97d9c35b9da40a0d75) on the same branch. I tried to explain what I did. I also battle-tested the exercise against different ways of getting it wrong, and the SCT behaves well. Let me know if you have follow-up questions!
