### ISSUE TITLE
SCT issue - involves multiple print statements with functions called inside of print

### ISSUE THREAD

**Issue by klmedeiros** [datacamp/pythonwhat#316]
In Data Types for Data Science, I have an exercise (chapter 3 ex 9) where I have 4 `print()` statements and multiple functions called inside of those `print()`s.

Here's the full solution code:
```
# Print the first key in ridership_date
print(list(ridership_date.keys())[0])

# Pop the first item from ridership_date and print it
print(ridership_date.popitem(last=False))

# Print the last key in ridership_date
print(list(ridership_date.keys())[-1])

# Pop the last item from ridership_date and print it
print(ridership_date.popitem())
```

I need to allow for some flexibility in this code, specifically to allow for `print(ridership_date.popitem(last = True))` in the last `print()` statement, which is currently filed as an issue [here](https://github.com/datacamp/courses-data-types-for-data-science/issues/75).

I switched the SCTs to use the `check_*` syntax, but I'm struggling with allowing for this flexibility, and for checking the code inside the `print()` statements, all of which the student must produce themselves.

I'm working on the [maintenance](https://www.datacamp.com/teach/repositories/906/branches/maintenance#builds) branch in teach right now, if you'd like to see where I'm at with this. I feel like this should be a `test_correct()`, but nothing I tried got me anywhere significant. (If this is too complicated, I'm happy to just remind students again NOT to use `last=True` in that last `print()` call.

**Comment by filipsch** [comment]
See https://github.com/datacamp/courses-data-types-for-data-science/pull/76
