### ISSUE TITLE
Support for IPython Magic Commands

### ISSUE THREAD

**Issue by filipsch** [datacamp/pythonwhat#33]
Related to issue posted by @hugobowne 
datacamp/pythonwhat#31

Python Magic Commands, such as ! ls are not supported due to `ast`, used for parsing.

This is a pain in the ass to support, so will take a long time.

**Comment by machow** [comment]
This should probably be treated as an issue of implementing an additional backend, since something like `!ls` should rightfully return an error in all courses that are teaching standard CPython.
