### ISSUE TITLE
solution code not accepted with test_function: BLOCKING BETA TEST 06/28

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#35]
https://campus.datacamp.com/courses/importing-data-into-python/introduction-and-flat-files?ex=13

(issue w/ line 7)

<img width="1253" alt="screenshot 2016-06-23 12 14 24" src="https://cloud.githubusercontent.com/assets/4182382/16310813/0fbe1cd6-393c-11e6-8c74-8bc6fe26e399.png">

the weird thing is that the exact same SCT works perfectly in this exercise:

https://campus.datacamp.com/courses/importing-data-into-python/introduction-and-flat-files?ex=16

**Comment by vincentvankrunkelsven** [comment]
Use `do_eval = False`. `np.genfromtxt(file , delimiter = ",", names = True , dtype = None)` is not the same two times, even with `numpy.testing.assert_equal`. 

```
import numpy as np
np.assert_equal(np.genfromtxt(file , delimiter = ",", names = True , dtype = None), np.genfromtxt(file , delimiter = ",", names = True , dtype = None))
```

Throws an `AssertionError`.

**Comment by hugobowne** [comment]
thanks. it works now: but aren't we testing type(data) == type(data), not that the arrays are equal?

**Comment by vincentvankrunkelsven** [comment]
`type(data)` is an argument of `print()`, so you're testing what you're suggesting with `test_function("print", ...)`. With `test_function("type", ...)`, you're testing the argument of `type(...)`, which is `data`.

**Comment by vincentvankrunkelsven** [comment]
It will be live on Monday. I've tested your SCT with the fix and it worked so you don't have to change that. I'm currently at home and can't seem to reach the VPN here, which I need to push to production. Once in the office again on Monday I'll push it first thing in the morning :-).

**Comment by hugobowne** [comment]
gr8 thx sounds good to me have a nice weekend!!

**Comment by vincentvankrunkelsven** [comment]
Your SCT should work now

**Comment by vincentvankrunkelsven** [comment]
Woooops those last two comments of mine should've been on #36. This issue was closed, right?
