### ISSUE TITLE
Solution note accepted: 'function NOT in solution env': BLOCKING BETA 06/28

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#36]
https://campus.datacamp.com/courses/importing-data-into-python/interacting-with-apis-to-import-data-from-the-web?ex=16

<img width="1245" alt="screenshot 2016-06-23 12 21 15" src="https://cloud.githubusercontent.com/assets/4182382/16311060/00223950-393d-11e6-836c-37b482371b85.png">

thought this may be a product issue but if i remove SCT, it works fine

**Comment by vincentvankrunkelsven** [comment]
Everything after `+=` wasn't parsed for to find function calls. Your SCT will work when we deploy this fix on production. @filipsch I've pushed fix to master, maybe we can deploy on production once you finished your `test_object_accessed()` function?

**Comment by hugobowne** [comment]
thx. when will this be on production? blocking my course

**Comment by filipsch** [comment]
@vincentvankrunkelsven I'm not sure when I'll have finished this function (busy week ahead), so go ahead and deploy!

**Comment by hugobowne** [comment]
@vincentvankrunkelsven i think this is fixed now. is it? :-D

**Comment by vincentvankrunkelsven** [comment]
It is! I accidentally commented on #35 instead of this issue!
