### ISSUE TITLE
Unable to Install 

### ISSUE THREAD

**Issue by WebDragonStudios** [datacamp/pythonwhat#363]
Hello, 

I'm running into errors when trying to install via the command line. Can you please advise? The following is there error message I'm receiving:

Command python setup.py egg_info failed with error code 1 in /tmp/pip-rCyH5R-build
Storing debug log for failure in /home/codio/.pip/pip.log
codio@edgar-nothing:~/workspace$ sudo pip install git+https://github.com/datacamp/pythonwhat
Downloading/unpacking git+https://github.com/datacamp/pythonwhat
  Cloning https://github.com/datacamp/pythonwhat to /tmp/pip-tqzVOf-build
  Running setup.py (path:/tmp/pip-tqzVOf-build/setup.py) egg_info for package from git+https://github.com/datacamp/pythonwhat
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-tqzVOf-build/setup.py", line 12, in <module>
        with open(path.join(HERE, 'README.md'), encoding='utf-8') as fp:
    TypeError: 'encoding' is an invalid keyword argument for this function
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-tqzVOf-build/setup.py", line 12, in <module>

    with open(path.join(HERE, 'README.md'), encoding='utf-8') as fp:

TypeError: 'encoding' is an invalid keyword argument for this function

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-tqzVOf-build
Storing debug log for failure in /home/codio/.pip/pip.log

**Comment by hermansje** [comment]
This project is built using Python 3.
From the error you have, it looks like you are using Python 2.

**Comment by WebDragonStudios** [comment]
Thank you, that was the issue.
