### ISSUE TITLE
Solution code not accepted: I/O error -- BLOCKING BETA 06/28

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#37]
https://campus.datacamp.com/courses/importing-data-into-python/introduction-and-flat-files?ex=3

<img width="1252" alt="screenshot 2016-06-23 12 24 00" src="https://cloud.githubusercontent.com/assets/4182382/16311174/7f0dd15c-393d-11e6-8512-c5a66fe8e6f6.png">

i thought this may be product issue but I removed SCT and it works fine then

**Comment by vincentvankrunkelsven** [comment]
Using `do_eval = False` on all the `print()` statements should work.

**Comment by hugobowne** [comment]
it did work! thx thats great.

ill close issue but can you explain whats happening here?

**Comment by hugobowne** [comment]
i think we may have discussed something similar b4 but can't remember :-/

**Comment by filipsch** [comment]
@hugobowne If you run the submission, by the end the file is closed again. After that, the SCT is run. `test_function()` will try to evaluate the argument, being `file.read()`. But `file` is closed, so `file.read()` generates an error.
