### ISSUE TITLE
The easy way to extract the message associated with "TestFail"

### ISSUE THREAD

**Issue by sayakpaul** [datacamp/pythonwhat#371]
Hi.

When a test fails (i.e. the submission code does not conform to the solution code) I get a long error stack. So, instead of that if I directly want to navigate to the message associated with `TestFail` what would be the easy way to do that? 
![image](https://user-images.githubusercontent.com/22957388/52045831-50de8700-256b-11e9-90e0-edbf94e081fc.png)

**Comment by hermansje** [comment]
You would wrap your code in a try-catch to handle the `TestFail` exception and extract the information you want from the exception.

**Comment by sayakpaul** [comment]
Sure. That sounds good.
