### ISSUE TITLE
Specifying filenames to setup_state()

### ISSUE THREAD

**Issue by sayakpaul** [datacamp/pythonwhat#372]
Hi.

Currently, as per the documentation, I am setting up local code-base pairs (submission code and solution code) like the following:
```python
# For local setup
from pythonwhat.local import setup_state

setup_state(stu_code = "import pandas as pd\
                        \npd.DataFrame([1, 2, 3], columns=['a'])", \
            sol_code = "import pandas as pd\
                        \npd.DataFrame([1, 2, 3], columns=['a'])")
```

I wanted to know if there is any provision to pass paths of the respective `.py` files to `stu_code` and `sol_code`. For example - 

```python
setup_state(stu_code = "stu_code.py", sol_code = "sol_code.py")
```
(I assume the files `stu_code.py` and `sol_code.py` are present in the same directory from where I will executing my experiments.)

And `stu_code.py` and `sol_code.py` would contain - 
```python
import pandas as pd
pd.DataFrame([1, 2, 3], columns=['a'])
```

**Comment by hermansje** [comment]
That functionality is not part of the library.
You can of course read any files you want and pass their content to the function you're using.

**Comment by sayakpaul** [comment]
Good to know about that.
