### ISSUE TITLE
Syntax Error Diagnostics and Suggestions

### ISSUE THREAD

**Issue by filipsch** [datacamp/pythonwhat#42]
If the student submits code that contains a syntax error, the student will get to see rather cryptic Python interpreter information, that is not necessarily helpful for the student.

Similar to `testwhat`, we'll want a tool that wraps around syntax error, providing more diagnostics.
This is a tough nut to crack.

**Comment by machow** [comment]
The most actionable type of feedback might be automatically informing students when they haven't filled in a blank (as in testwhat).
