### ISSUE TITLE
Specify arguments explicitly inside `test_function()`

### ISSUE THREAD

**Issue by filipsch** [datacamp/pythonwhat#43]
@hugobowne @vincentvankrunkelsven 
Currently, `test_function()` tests all arguments when you don't specify the `args` argument.
The more I'm looking at it, however, it seems to be clearer, more straightforward to right and more intuitive to have SCT authors explicitly say which arguments and which keywords they want to check.
What do you think?

For backwords compatibilty, we can go through the SCTs that are live today, make the keywords and args explicit, put those live, and then rewrite `test_function()`.

**Comment by hugobowne** [comment]
This would great. How does it work in testwhat wrt giving tailored feedback for incorrect arguments?  I think that this will be a related issue: https://github.com/datacamp/pythonwhat/issues/44

I know it may be unorthodox workflow but it may be worth actually discussing this in person/skype. happy to pass by jo :-)

**Comment by filipsch** [comment]
@hugobowne Yes I'm still working on #44 , but because there's `args` and `keywords` you can check, how you have to list the incorrect arguments is not very clear. I'll elaborate on it there.

**Comment by filipsch** [comment]
The new version of `test_function()`, creatively named `test_function_v2()`, requires you to explicitly specify which function parameters have to be specified. This function is now on staging. Documentation will come soon.

**Comment by filipsch** [comment]
`test_function_v2()` has been documented [here](https://github.com/datacamp/pythonwhat/wiki/test_function_v2), function will be on production later today.
I will carefully rewrite the `test_function()` calls in the SCTs of intro and intermediate python, to see if it works ok.

**Comment by filipsch** [comment]
It's live. Read about it [here](https://github.com/datacamp/pythonwhat/wiki/test_function_v2)
