### ISSUE TITLE
Use exception handling to improve flow

### ISSUE THREAD

**Issue by filipsch** [datacamp/pythonwhat#48]
Each time a function like `test_function()` runs a test, it gets back a result. If this result is False, the function will be exited, with `not result`. This works, but it requires you to explicitly do this after each test. It would be better if asesrtions fail with a certain Error, so that it can be handled with exception handling. (SCTException).

**Comment by machow** [comment]
While implementing the exception raising, I noticed this line in a few files...

```
if not rep.feedback.line_info:
    rep.feedback = Feedback(rep.feedback.message, subtree_student)
```

But when I remove it the tests still pass. @filipsch what does this do? Add line_info if sub tests didn't? If it's used, I'll add a couple unit tests to make sure the exception handling doesn't screw it up.
