### ISSUE TITLE
test_student_typed not working

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#50]
I have tried to reproduce this

*** =sct
```{python}
test_student_typed(/sum\s*\(\s*range\s*\(/, not_typed_msg="You didn't use `range()` inside `sum()`.")
success_msg("Great job!")
```

from [this page](https://github.com/datacamp/pythonwhat/wiki/test_student_typed) and it doesn't work.

See [here](https://github.com/datacamp/courses-introduction-to-relational-databases-in-python/blob/SCT_test/chapter1.md) and [here](https://campus.datacamp.com/courses/1380/3286?ex=3). 

I tried by putting quotations marks around the regex and still doesn't work

**Comment by filipsch** [comment]
@hugobowne this is an error in the wiki, apologies for this. It has been fixed: [link to wiki](https://github.com/datacamp/pythonwhat/wiki/test_student_typed)

If you want to use a regular expression, you also have to use the double quotes, but not the forward slashes:

```
test_student_typed("sum\s+\(\s*range\s*\(")
```

I added tests to the pythonwhat package (see [here](https://github.com/datacamp/pythonwhat/commit/1c924da84776a978b28f78c9f3915227758f2d87)), so should be working fine.

**Comment by hugobowne** [comment]
:+1:
