### ISSUE TITLE
Scratch pad for pythonwhat

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#51]
to demonstrate an [issue](https://github.com/datacamp/pythonwhat/issues/50) that wasn't totally related to my course, I needed to create a branch and write an SCT there.

It would be great to have a place where we could write SCTs to demonstrate issues

**Comment by filipsch** [comment]
There's no need to create an entire branch to show one thing.
I suggest you basically create a dummy course,  `courses-pythonwhat-issues` or something, that everyone has access to. You can then add and remove problematic usecases as you want, as it is not live content.
I think making something new for this is overkill..

**Comment by hugobowne** [comment]
great idea will do
