### ISSUE TITLE
Test methods and chained methods

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#54]
Let's say that the solution code has

```
tables = connection.execute(stmt).fetchall()
```

How would we test that the correct methods are applied in the correct order? Can `test_function` do this?

In our sqlalchemy course, this will be necessary in more than 50% of the exercises.

Note: my intern Vincent is currently working on these SCTs and has tried `test_student_typed` but it isn't quite working. See [this issue](https://github.com/datacamp/pythonwhat/issues/50). any suggestions?

**Comment by filipsch** [comment]
I currently don't believe that there is an easy way to test 'chained' commands like this, I'll try to add it soon.  You could use `test_student_typed()` as a current fix, but I wouldn't recommend it. The issue you referenced is resolved by now, so you could try with that.

**Comment by hugobowne** [comment]
thanks @filip-- much of our sqlalchemy course uses chained commands, fyi.

could you provide a provisional timeline for this feature? it will help me figure out what tasks my intern should be currently doing

**Comment by filipsch** [comment]
I'd say by July 27? Does that work?

**Comment by hugobowne** [comment]
@filipsch that works wonderfully

**Comment by filipsch** [comment]
@hugobowne I made changes to the function call parser so that you can use `test_function()`. Currently, changes are on staging but will move them to master if you're ok with them.

For your specific example, the SCT would be:

```
test_function("connection.execute", do_eval = False)
test_function("connection.execute.fetchall")
```

Notice that in the first function call, you need `do_eval = False` because there is no equality defined for the type that `stmt` has. 

Notice from the second function call that you have to describe the entire chain (leaving out the arguments that are passed to `execute`). This way, you explicitly list the order in which the methods should be called. 

Does this look good?

I couldn't figure out a straightforward way to generate meaningful automated feedback messages if you didn't call the `fetchall()` or `execute()` method in the first place; I suggest you override those with your own.

**Comment by hugobowne** [comment]
@filipsch this is working well now. i'll try overriding feedback and see if i can come up with anything automated and nice

**Comment by hugobowne** [comment]
@filipsch 

there are also many cases where chained methods are used as arguments passed to functions.

e.g.

```
stmt = select([census.columns.state, (census.columns.pop2008-census.columns.pop2000).label('pop_change')]).group_by(census.columns.state).order_by(desc('pop_change')).limit(5)
```

do you have any suggestions for working with these, that is, giving specific feedback wrt methods used in arguments? I thought we could define all arguments prior to calling function but this is non-standard and not what we should be teaching

**Comment by filipsch** [comment]
@hugobowne currently, being able to give feedback to "the method inside the list that is an argument of another method", this deep, is totally not possible.

To allow for this, I've been working on in a next iteration of pythonwhat, where you can dive as deep as you want into some function calls, arguments, methods, whatever. You can read up on it [here](https://datacamp.atlassian.net/wiki/pages/viewpage.action?pageId=46006314) and I'll also talk about it during the CE update.

Short answer: No, not possible, but hopefully soonish (end of august).

**Comment by hugobowne** [comment]
@filipsch 

1. timing is fine: this course won't be launched until end of august so I may be able to delay launch slightly. We can discuss more closer to date. Should i raise another issue where we can discuss this specifically?

2. Chained methods now working well on master: is there documentation for this functionality?

**Comment by filipsch** [comment]
@hugobowne

1. You can leave it here; this is an issue that'll probably solves itself when the new implementation is there, and ideally won't need a specific treatment. I'll close the issue when appropriate.
2. I've just updated the article on the wiki with the example that is shown here. https://github.com/datacamp/pythonwhat/wiki/test_function#example-4-methods

**Comment by machow** [comment]
Here is a [documented solution](https://datacamp.github.io/courses-pythonwhat-tutorial/testing-functions-and-packages.html#Testing-method-calls-(2)) for testing method chains using `has_equal_ast`. Note that check_function and test_function can be used to select chained methods, (e.g. `connection.execute`). See [here](https://datacamp.github.io/courses-pythonwhat-tutorial/testing-functions-and-packages.html#Testing-method-calls-(1))
