### ISSUE TITLE
Testing user-defined errors: block beta testing 08/17

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#56]
can we test raising errors in user-defined functions?

First example would be using `try`-`except`. see here for more details:

https://docs.python.org/3/tutorial/errors.html

**Comment by filipsch** [comment]
Will try to get something working by beginning of next week, i.e. August 8

**Comment by filipsch** [comment]
Implemented and available on staging, soon on master.
[Wiki article on `test_function_definition()`](https://github.com/datacamp/pythonwhat/wiki/test_function_definition#example-2-user-defined-errors) has been updated.

In short, you can check if certain function calls raise an error, and whether the type of this error (`ValueError`, `NameError`, etc) corresponds to the type of error that is raised by the solution.

I figured doing actual checks on the messages that the errors generate would take us too far in customizing `test_function_definition()`; this will become possible in the big rework of `pythonwhat`.

**Comment by filipsch** [comment]
Will go live tomorrow.
