### ISSUE TITLE
IPython magic shell commands

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#6]
With IPython, you call execute Shell commands by prefacing them with `!`, e.g. `! ls` for directory contents. 

I use this in my course and Hamel will use it in his Cleaning Data in Python course.

We will need some test functions for this.

**Comment by vincentvankrunkelsven** [comment]
Is this only `! ls`? You can use `test_student_typed()` for this.

**Comment by hugobowne** [comment]
there'll be more cases. Hamel will use commands from csvkit and csvfix for his course:

http://csvkit.readthedocs.io/en/0.9.1/tutorial.html

http://neilb.bitbucket.org/csvfix/

the 1st has a python package but it may have less functionality than the shell toolkit. i'll know more when he gets back from vacation

**Comment by vincentvankrunkelsven** [comment]
I'll look in to it. Also if you want to use another "magic" command than `!` for system operations, be sure to first check with product on the `pythonbackend` GitHub. Some of these might not be supported.

**Comment by filipsch** [comment]
@vincentvankrunkelsven @hugobowne this can become challenging as `ast`, the syntax parser that we use to parse a submission, does not recognize IPython commands (give a syntax error in this case). So we need to make sure to work around them.

**Comment by hugobowne** [comment]
ahhhh wait I just raised this in a new issue:  https://github.com/datacamp/pythonwhat/issues/31

because the error message is now thrown. feel free to merge issues

**Comment by vincentvankrunkelsven** [comment]
Moved to #33
