### ISSUE TITLE
Testing generator expressions: block beta testing 08/17

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#61]
SCT needed for generator expressions such as

```
result = (num for num in range(31))
```

**Comment by filipsch** [comment]
Generator functions and list comprehensions are very close in Python syntax, so I'll try to have a very similar thing for these. Before I do that, can you answer some of the additional questions I've asked in #60 ? Thanks.

**Comment by filipsch** [comment]
@hugobowne functionality has been written, it's under review now and will go live with the big update of pythonwhat, hopefully beginnen of next week.
You can already read up on it in the wiki:
https://github.com/datacamp/pythonwhat/wiki/test_comprehension
If I close this issue, this means the feature will be available on production.
