### ISSUE TITLE
Testing user-defined generator functions: block beta testing 08/17

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#62]
SCT needed for user-defined generator functions such as

```
# Create a list of strings
lannister = ['cersei', 'jaime', 'tywin', 'tyrion', 'joffrey']

# Define generator function get_lengths
def get_lengths(input_list):
    """Generator function that yields the
    length of the strings in input_list."""

    # Yield the length of a string
    for person in input_list:
        yield len(person)
```

User-defined functions already good so maybe just `yield` necessary?

**Comment by hugobowne** [comment]
Also need to test `break`:

```
def read_large_file(file_object):
    """
    Uses a generator to read a large file lazily
    """
    while True:
        data = file_object.readline()
        if not data:
            break
        yield data
```

**Comment by filipsch** [comment]
Hey @hugobowne , not sure if extra functionality is required here.
You can simply use `test_function_definition()` and then use 
- `test_student_typed()` for `yield`
- The `results` parameter to test the output for different inputs.
- `test_student_typed()` for `break`?

**Comment by hugobowne** [comment]
@filipsch i'm not `test_student_typed` is appropriate.  they could write `yield` and `break` in the incorrect places and the SCT would not pick this up. the `results` parameter MAY pick it up
but then we wouldn't necessarily know which error message to supply.

Also, if we have an exercise where they need to write 2 functions using `yield` and/or `break`,
this won't work

thoughts?

**Comment by filipsch** [comment]
@hugobowne 
- If they have to write two functions, you can use `test_function_definition()` twice, once with `index = 1` and once with `index = 2`, and their treatments would be totally separate.
- If you don't want to use `test_student_typed()` inside the `body` test of `test_function_definition()` and use `results`, `outputs` and `errors` arguments to test for different submissions (which I would still propose): how are you going to test the correct location of `yield` and `break` anyways then? There is no single way that people can write a function, they can place `break` and `yield` at different locations; we have to do this through indirect checking I think...

**Comment by filipsch** [comment]
@hugobowne I will not write dedicated functionality for this, as it feels like the workaround are sufficient.
