### ISSUE TITLE
Problem with test_correct: blocking my brain

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#67]
hi friend!

I am having a serious challenge with `test_correct`.

In this [exercise here](https://campus.datacamp.com/courses/1533/3850?ex=7), the `test_correct` SCT seems to break DataCamp.  [Here is the code](https://github.com/datacamp/HBA-python-problem-playground/blame/master/chapter1.md#L306).  

I only have this issue when  I am using custom functions, FYI. You can see in line 388 that I use the following:

```
test_correct(lambda: test_object('df'), df_diag())
```
where `df_diag` is a custom function. I have also tried using 
```
test_correct(lambda: test_object('df'), lambda: df_diag())
```
and this doesn't work either. I think that this displays my ignorance also about the necessary use of lambda functions in pythonwhat SCTs so perhaps you could explain this and we could add to documentation.

The stranger aspect is that the 2nd version above seems to work when used in a context manager!!
See [here](https://campus.datacamp.com/courses/1533/3850?ex=10) and the code is [here](https://github.com/datacamp/HBA-python-problem-playground/blame/master/chapter1.md#L650). Do you know why it works within a context manager?

thanks!

**Comment by filipsch** [comment]
Hey Hugo,

You should use:

```
test_correct(lambda: test_object('df'), df_diag)
```

`test_correct()` expects **functions**, either lambda or function definitions, so you have to pass `df_diag`, not `df_diag()`. Does it work then?

**Comment by filipsch** [comment]
I added an article to the wiki about it
https://github.com/datacamp/pythonwhat/wiki/Sub-SCTs

**Comment by hugobowne** [comment]
this works wonderfully!
