### ISSUE TITLE
Issue with test_or

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#68]
Hi, you can see in Issue #67 that i am currently challenged by `test_correct`. This led me to attempt to implement the same SCT using `test_or`.

[Here is the DC exercise](https://campus.datacamp.com/courses/1533/3850?ex=8) and [here is the code](https://github.com/datacamp/HBA-python-problem-playground/blame/master/chapter1.md#L395)

I use 
```
test_or(lambda: test_object("df"), df_test())
```
where `df_test` is custom.

To my understanding, if `df` is the same in sample&solution, the SCT should pass. However,
if I alter `rs = con.execute("SELECT * FROM Album")` to `rs = con.execute("SELECT * from Album")`, I get the following:

<img width="1264" alt="screenshot 2016-08-30 10 48 34" src="https://cloud.githubusercontent.com/assets/4182382/18072172/5869a9ee-6e9f-11e6-93f5-e7a6b6b1c4a5.png">

any idea what's happening here?

thanks!

**Comment by filipsch** [comment]
Same here, you have to use

```
test_or(lambda: test_object("df"), df_test)
```

Pass the function itself, not the result of calling the function.

**Comment by filipsch** [comment]
I added an article to the wiki about it
https://github.com/datacamp/pythonwhat/wiki/Sub-SCTs

**Comment by hugobowne** [comment]
fantastic!
