### ISSUE TITLE
question mark missing in default response to test_import

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#69]
when i use `test_import`, the default response looks as follows and needs to have a question mark:

<img width="470" alt="screenshot 2016-09-01 15 40 16" src="https://cloud.githubusercontent.com/assets/4182382/18156603/b591363e-705a-11e6-964c-39df2d97d311.png">

from this exercise: https://campus.datacamp.com/courses/1691/4439?ex=13

this is odd because i dont think that it was always like this

**Comment by filipsch** [comment]
@hugobowne I think it's a typo that has always been around. It's fixed now. Will go live together with all the other stuff, September 5th.
