### ISSUE TITLE
Issue with test_function_definition: BLOCKS BETA 9/7

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#71]
`test_function_definition()` is an incredible function! It's working beautifullly in general, however there is an issue:

see [this exercise](https://campus.datacamp.com/courses/1532/3847?ex=7) and the ones that follow it.

And [here is the SCT code](https://github.com/datacamp/courses-pythonista-data-science-toolbox-I/blame/master/chapter1.md#L363)

To test within the function definition that the student defines 'shout_word' correctly, I use `test_object_after_expression()` because, as I understand, `test_object()` doesn't currently work due to scoping issues (is this correct?)

I use an argument for the parameter `undefined_msg` which I get from [here](https://github.com/datacamp/pythonwhat/blob/master/pythonwhat/test_object_after_expression.py) (I can't find any information on wiki about `test_object_after_expression()`). However when, in the function definition, I don't define `shout_word`, DataCamp crashes:

<img width="1257" alt="screenshot 2016-09-01 17 13 52" src="https://cloud.githubusercontent.com/assets/4182382/18158582/83389f44-7067-11e6-898a-022ede8d9ac1.png">

Any ideas? thanks, guys!

**Comment by filipsch** [comment]
@hugobowne This is a bug in Python, i've fixed it and it will go live with the other stuff Monday Sep 5 !
The SCT is perfectly fine. I'll also update the wiki to give an example about `test_object_after_expression()`.

**Comment by filipsch** [comment]
https://github.com/datacamp/pythonwhat/wiki/test_object_after_expression
