### ISSUE TITLE
Nested functions issue II: BLOCK BETA 9/7

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#73]
a different issue with nested functions: im trying to `test_object_after_expression()` in a nested function. [Exercises here](https://campus.datacamp.com/courses/1533/3850?ex=15) and [code](https://github.com/datacamp/HBA-python-problem-playground/blame/master/chapter1.md#L1024). I am trying to test the correct assignment of 'echo_word'.

I have tried using the `context_vals` arg in a number of ways and none seem to work.

Ideas?

**Comment by hugobowne** [comment]
OK! I managed to figure this out. I used `extra_env = {'n' : 1}` within `test_object_after_expression()`

Going back to the wiki [here](https://github.com/datacamp/pythonwhat/wiki/test_object_after_expression), the use of `extra_envs` is kind of suggested for this case, but the language is obscure (Through extra_env and context_vals you can adapt the student/solution environment with manual elements. Next, the 'currently active expression tree', such as the body of a for loop, is executed, and the resulting environment is inspected. ) I definitely did not understand to use `extra_envs` as it is not really explained.

Use of it occurs in one example on the same page but I found that similiarly opaque. I'm not suggesting we edit the wiki right now because I'm not sure of the best way to approach this but I want to flag it as I have spent hours figuring out how to solve this.

**Comment by filipsch** [comment]
Okay, let me know when you have any suggestions.
It's all pretty funky stuff, and it's hard to explain.
