### ISSUE TITLE
context_vals: ability to pass list of lists of vals, to test multiple initializations at once

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#75]
When using `test_object_after_expression()`, the argument `context_vals` allows me to specify, for example, function arguments to use when test the object:

> It's a simple list: the first element of the list will be the value for the first argument of the function definition, the second element of the list will be the value for the second argument of the list, and so on. 

Is there any way to test multiple possibilities for arguments? I know that I could call `test_function_definition()` twice, for example, or `test_object_after_expression()` twice but this seems overkill.

Some information here: https://github.com/datacamp/pythonwhat/wiki/test_object_after_expression

**Comment by filipsch** [comment]
I'm not sure what the problem is?
If we want to test multiple possibilities, you should indeed use `test_object_after_expression()` twice; there's no way to test several instantiations of `context_vals` inside the same `test_object_after_expression()`.

**Comment by hugobowne** [comment]
ok. I was thinking one could pass `context_vals` a list of lists, which could scale if I wanted to test over a pre-defined sequence, for example

**Comment by filipsch** [comment]
That would be similar to how `test_function_definition()` does it, truth. I'll keep this as a possible improvement of the function, but for now, stick with `test_object_after_expression()` twice, ok?

**Comment by hugobowne** [comment]
Sounds good to me.

**Comment by filipsch** [comment]
I had a look with @machow, who will take over the `pythonwhat` package soon.
Suppose you want to do something like this:

```python
test_object_after_expression('shout_word', context_vals = [['test'], ['test2']])
```

telling `pythonwhat` to run `test_object_after_expression()` twice; once for context vals `['test']`, and once for context vals `['test2']`. However, this is ambiguous. It should be perfectly possible to set two context vals, that are each a list. So simply wrapping this in a list will make things ambiguous (is it a set of context vals for a single case, or single context vals for different cases?).

If you have a case where you want to test a bunch of different possibilities, you can wrap around it yourself (for example using the `partial` function in the `functools` package.)

**Comment by machow** [comment]
I wonder if there are some differences in default behaviors that might cause the kind of confusion raised in this issue. 

The `results` argument of `test_function_definition` expects a list of sets of arguments to test on a user-defined function (e.g. `[args1, args2]`, where it will first test with `args1`). But in this case, that means if you had actually wanted to test a function with a single argument, `[args1, args1]`, you would need to wrap it in another list, `[[args1, args2]]`. 

Not worth re-opening, since changing would break backward compatibility, but it may be worth documenting as some point.

**Comment by filipsch** [comment]
@machow Totally agree!
