### ISSUE TITLE
SCT bugs

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#77]
I keep encountering bugs similar to the one discussed in #71 -- 'line_end' error, for example. Here's one of many:
<img width="1270" alt="screenshot 2016-09-05 18 38 00" src="https://cloud.githubusercontent.com/assets/4182382/18242091/f7d3ad20-7397-11e6-8ea5-72ca646ed969.png">

I won't raise them all as issues because this will fixed with the new deployment, right?

I am raising this particular issue so that you can let me know here when deployment has occurred, after which I will report all issues that I encounter.

**Comment by filipsch** [comment]
Will be fixed in new deployment.
