### ISSUE TITLE
Exception handling with try-except: BLOCK BETA 9/9

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#80]
The error handling in user-defined functions is great! See [here](https://campus.datacamp.com/courses/1692/4444?ex=10) for a very nice example (I'm also using `test_function_v2()` in here, FYI!)

This is related to #56 : that issue was initially requesting pythonwhat functionality for testing students using `try-except` to handle exceptions. I can't find this anywhere but I may be missing something. The idea is to test the following:

```
# Define shout_echo
def shout_echo(word1, echo=1):
    """Concatenate echo copies of word1 and three
    exclamation marks at the end of the string."""

    # Initialize empty strings: echo_word, shout_words
    echo_word = ''
    shout_words = ''

    # Add exception handling with try-except
    try:
        # Concatenate echo copies of word1 using *: echo_word
        echo_word = word1 * echo

        # Concatenate '!!!' to echo_word: shout_words
        shout_words = echo_word + '!!!'
    except:
        # Print error message
        print("word1 must be a string and echo must be an integer.")

    # Return shout_words
    return shout_words
```

thanks!

**Comment by filipsch** [comment]
@hugobowne So you mean a function

`test_try_except()`, where you can pass subSCTs for the `try`, `except` and `finally` block?

**Comment by hugobowne** [comment]
@filipsch I think this could be a good solution. The idea would be to pass such a `test_try_except()` to the `body` parameter of `test_function_definition()`, right?

**Comment by filipsch** [comment]
yes indeed, nesting ftw.

**Comment by filipsch** [comment]
@hugobowne I've added the functionality to `pythonwhat`, hopefully live tomorrow with all the other stuff.
Wiki here: https://github.com/datacamp/pythonwhat/wiki/test_try_except
