### ISSUE TITLE
Nested functions issue III: BLOCK BETA 9/15

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#85]
Related to #74 -- `nonlocal` still isn't quite working. 

exercise:
https://campus.datacamp.com/courses/1533/3850?ex=15

code:
https://github.com/datacamp/HBA-python-problem-playground/blame/master/chapter1.md#L1115

See screenshot:

<img width="1279" alt="screenshot 2016-09-12 18 55 34" src="https://cloud.githubusercontent.com/assets/4182382/18430205/d7dec42c-791a-11e6-8349-906a4b764f9a.png">

**Comment by filipsch** [comment]
Hey @hugobowne, it appears that I didn't write a test for the fix I did, and there was a small typo in my code. I've fixed it and hopefully live by tomorrow morning Belgian time.

**Comment by hugobowne** [comment]
thx!

**Comment by hugobowne** [comment]
@filipsch still same issue: ETA?

**Comment by filipsch** [comment]
Not live yet

**Comment by filipsch** [comment]
Not live yet, should be there by noon Belgian time. It's still early here.

**Comment by filipsch** [comment]
should be live now.
