### ISSUE TITLE
test function defn with test try except issue: BLOCK BETA 9/15

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#86]
I'm trying to use `test_try_except()` within `test_function_definition()`.

I am using this as a model: https://github.com/datacamp/pythonwhat/wiki/test_try_except

No luck yet!

It seems to tell me 'name collections is not defined' : 
<img width="1276" alt="screenshot 2016-09-12 20 27 16" src="https://cloud.githubusercontent.com/assets/4182382/18432791/6b441fbc-7927-11e6-8da1-b236acb1b6a9.png">

SCT is here, Ch3 line618: https://www.datacamp.com/teach/edit/repositories/463/branches/SCT_edits

You get (10**100000)! points for using `collections`, one of my favourite python modules, if not my favourite 👍

**Comment by filipsch** [comment]
For some obscure reason that I can't explain myself, you have to put the `import collection` call inside the definition of `inner_test()`. It's probably a scoping issue, but I can't tell you what's really playing here.

`inner_test()` should look like this:

```python
def inner_test():
    def inner_inner_test():
        test_object_after_expression("echo_word", extra_env={'word1' : 'hithere', 'echo': 2})
    import collections
    handlers = collections.OrderedDict()
    handlers['all'] = lambda: test_function('print')
    test_try_except(index = 1,
                body = inner_inner_test,
                handlers = handlers)
```

**Comment by hugobowne** [comment]
works great thx good nice!
