### ISSUE TITLE
How pythonwhat throws errors

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#89]
A significant part of my current SCT-writing workflow involves my trying to figure out what is wrong with my SCT. To do so, I look at the faded out text in the IPython shell (screenshot). As it's faded and covered by other text, it's always difficult to read (sometimes not even possible). Most of the time, when I can read it, it doesn't tell me what the problem with my SCT is (e.g. which line). I'm sure that this is highly non-trivial to solve but I thought to let you know that, in the long term, it would be great to be able to debug SCTs in a more user-friendly manner.

<img width="647" alt="screenshot 2016-09-19 10 55 44" src="https://cloud.githubusercontent.com/assets/4182382/18636680/b32a4d6c-7e57-11e6-99b9-550b7a1069fc.png">

**Comment by machow** [comment]
Similar to issue #42

**Comment by machow** [comment]
as Hugo mentioned, appears fixed on teach app
