### ISSUE TITLE
test_expression_result on wiki

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#91]
I don't really understand the use of `test_expression_result()` in a `test_for_loop()`. It has been suggested that I use it in #70, #83, #90 and the usage is not explained in the wiki for `test_for_loop()` (it is mentioned once now but I think it's new). It would be helpful to explain it on this page and give some use cases.

There is also no wiki page on `test_expression_result()`, as far as I can see.

**Comment by filipsch** [comment]
I'll make sure to add it.

**Comment by filipsch** [comment]
Article for both `test_expression_output()` and `test_expression_result()` added, with two pretty detailed examples.
