### ISSUE TITLE
test_function_definition(): message if *args is specified incorrectly

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#93]
When defining a function that requires `*args`, the student passes `args~ instead, the error message is: 

![screenshot 2016-09-20 14 55 29](https://cloud.githubusercontent.com/assets/4182382/18684477/53c541ec-7f42-11e6-853a-0b1242d642fa.png)

This will confuse the student.

Check it out in [this exercise](https://campus.datacamp.com/courses/1532/3848?ex=12), for example. thoughts?

**Comment by filipsch** [comment]
That's because `*args` are considered special arguments, as is `**kwargs`.
For now, can you simply override the automatic messages inside `test_function_definition()`, more specifically the `nb_args_msg` argument? That way, this message won't appear.
We'll look into solving this later on then.

**Comment by machow** [comment]
This can be solved by something like

*** =solution
```{python}
def f(*args): pass
```

*** =sct
```{python}
Ex().check_function_def('f').check_args('*args', undefined_msg='did you define starred args?').has_equal_name(msg='did you name *args correctly?')
```

**Comment by machow** [comment]
documented: http://pythonwhat.readthedocs.io/en/latest/part_checks.html#function-definition-lambda-args
