### ISSUE TITLE
SCT for elements of list that is passed as argument: BLOCKS BETA 10/07

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#99]
When using SQLAlchemy to query DBs, we pass `select()` a list, e.g.

`stmt = select([func.count( census.columns.state.distinct())])`

I need to somehow write an SCT that tests that the elements of the lists are correct (I cannot pre-assign the list as not good practice to teach).

Ideally, I could use a `test_function("sqlalchemy.select", do_eval=False)` with a `test_correct()`. If `test_function("sqlalchemy.select", ...)` fails, then I could probe the list that is its 1st argument and test whether `func.count()` was used therein, for example.

Find here below another example in which the list has two elements. The example is complete with PEC, solution and current SCT.

Note when I write that this blocks beta testing, this is the date that i want to beta test, which means I would need to start writing these SCTs on 10/03 or thereabouts. If this functionality is NOT possible, lets try to work around it, because I need to get this course out.

*** =pre_exercise_code
```{python}
# pec
from urllib.request import urlretrieve
from sqlalchemy import create_engine, MetaData, Table, select, desc
filename = 'https://s3.amazonaws.com/assets.datacamp.com/production/course_1115/datasets/census.sqlite'
urlretrieve(filename, 'census.sqlite')
engine = create_engine('sqlite:///census.sqlite')
metadata = MetaData()
connection = engine.connect()
census = Table('census', metadata, autoload=True, autoload_with=engine)
```

*** =solution
```{python}
# Import func
from sqlalchemy.sql import func

# Build a query to select the state and count of ages by state: stmt
stmt = select([census.columns.state, func.count(census.columns.age)])

# Append group by state
stmt = stmt.group_by(census.columns.state)

# Execute the statement and store all the records: results
results = connection.execute(stmt).fetchall()

# Print results
print(results)

# Print the keys/column names of the results returned
print(results[0].keys())
```

*** =sct
```{python}
# sct code
test_import("sqlalchemy.sql.func", not_imported_msg="Did you import `func` from the package `sqlalchemy.sql.func`?")
test_function("sqlalchemy.select", do_eval=False, not_called_msg="Did you use the `select` statement to create `stmt`?")
test_function("stmt.group_by", do_eval=False)
test_object("stmt", do_eval=False, undefined_msg="Did you create the statement as `stmt`?")

test_function("connection.execute", do_eval=False)
test_function("connection.execute.fetchall", not_called_msg="Did you use `fetchall()`?")
test_object("results", incorrect_msg="Did you use `connection.execute(stmt)` and `fetchall()` correctly to get the `results`?")
```

Another example from [here](https://campus.datacamp.com/courses/1115/2470?ex=2):

```
stmt = select([census.columns.state, (census.columns.pop2008-census.columns.pop2000).label('pop_change')])
```

Another example from [here](https://campus.datacamp.com/courses/1115/2470?ex=3) that uses `func.sum()`, not `select()` (slightly different, but the principle of probing args is the same; actually, in this case, I'd like to be able to probe the list passed to `case()`, which is itself passed to `func.sum()`! Should I raise another issue?)
```
# Build an expression to calculate female population in 2000
female_pop2000 = func.sum(
    case([
        (census.columns.sex == 'F', census.columns.pop2000)
    ], else_=0))
```

thank you much!

**Comment by filipsch** [comment]
@machow It's going to be rather involved to add 'subtests' to `test_function()` to do more 'detailed' tests inside arguments of a function call.

As a workaround for this, @hugobowne suggested using `test_expression_output`, to just see if the printout of the `stmt` object contains the correct elements. It's a good idea, but to do it you need to tweak `test_expression_output()` so that you can override the default behavior that the output of the student is compared to the output of the solution (and instead use a regex).

**Comment by machow** [comment]
I agree--it seems better to implement this in the new spec, rather than making heavy revision to the current test functions.

It looks like the test_output_contains SCT uses regex, so it should be straightforward to copy from there?

**Comment by machow** [comment]
The points about probing the internals were really helpful. [Here is a jupyter notebook that shows how they could be used with your example](http://nbviewer.jupyter.org/gist/machow/1d51a482e4ba5b444ddfc4f9426df6f0).

@filipsch how would you eval an expression like `"len(stmt.columns) == 2"`, and test that it returns is `True` in the submission process environment?

**Comment by filipsch** [comment]
Would [`test_expression_result`](https://github.com/datacamp/pythonwhat/wiki/test_expression_result) work in this case?

```python
test_expression_result(expr_code = "len(stmt.columns) == 2")
```

**Comment by machow** [comment]
Definitely! I originally didn't notice in the docs where it mentioned that expr_code "overrides the default expression tree".  

In Hugo's case, it looks like he could use...

```
test_expression_result(expr_code = "len(stmt.columns)")
```

And it will compare the output length between the submission and the solution.

**Comment by machow** [comment]
let me know if you run into problems with this solution, will add to wiki

**Comment by hugobowne** [comment]
So my initial question was this:

> When using SQLAlchemy to query DBs, we pass `select()` a list, e.g.
`stmt = select([func.count( census.columns.state.distinct())])`
I need to somehow write an SCT that tests that the elements of the lists are correct (I cannot pre-assign the list as not good practice to teach).
Ideally, I could use a `test_function("sqlalchemy.select", do_eval=False)` with a `test_correct()`. If `test_function("sqlalchemy.select", ...)` fails, then I could probe the list that is its 1st argument and test whether `func.count()` was used therein, for example.

**Comment by machow** [comment]
[The jupyter notebook shows a number of expressions that can test different cases](http://nbviewer.jupyter.org/gist/machow/1d51a482e4ba5b444ddfc4f9426df6f0)

In the case of whether they have used `func.count()`, it seems like you could use

```{python}
test_expression_result(expr_code = "stmt.columns.has_key('count(census.age)')")
```

or

```{python}
test_expression_result(expr_code = "'count_1' in stmt.columns")
```

This issue is one that will largely require expertise about how to pull information out of SQLAlchemy objects. I don't really know SQLAlchemy well enough to say much about testing these objects in general, and used the comment by JM to investigate. 

Happy to pair and go over very quickly how I investigated the SQLAlchemy objects (on screenhero 😈 ).

**Comment by hugobowne** [comment]
@machow oh thx! I thought that link above was part of your conversation with filip. will make sure to check out
